### ISSUE TITLE
Failed to execute script gui

### ISSUE THREAD

**Issue by GrantCE** [google/spatial-media#100]
I have built this using PyInstaller on Windows 10 (latest Python 2.7.11).

When I click on Spatial Media Metadata Injector.exe I get the error "Failed to execute script gui".

I've not got much experience with Python - is there any more information I can give to figure out what's causing this?

**Comment by Julkeno** [comment]
I'm pretty sure i saw in an other issue that the PyInstaller doesnt work on Windows 10. :(

**Comment by suderman-google** [comment]
The newest version should support Windows 10 however there have been issues with the most recently released version. We will try to release a fix as soon as possible.
