### ISSUE TITLE
Windows Defender Found Malware in Software

### ISSUE THREAD

**Issue by messlin** [google/spatial-media#101]
Windows message Detected Item: Trojan:  "Win32/Rundas!plock" 

location:  /Spatial Media Metadata Injector.exe

Description: This program is dangerous and executes commands from an attacker.

**Comment by pwroberts** [comment]
Hi @messlin,

Thank you for reporting this. As discussed on https://github.com/google/spatial-media/issues/97, it looks like 32-bit PyInstaller packed binaries are occasionally getting flagged by some AV engines.

I've put a new, 64-bit Windows binary on [the 2.0 release page](https://github.com/google/spatial-media/releases/tag/v2.0). 32-bit Windows users can still run the injector from source by installing Python, as described on the release page.

Thanks again, and please do re-open this issue if you see any more AV warnings.

Paul

**Comment by kwaazaar** [comment]
This ís a virus currently being very active. So maybe it's more than just a false positive?
