### ISSUE TITLE
Metadata injector fails to work if username contains non-ASCII characters ("failed to execute script gui")

### ISSUE THREAD

**Issue by shedie** [google/spatial-media#106]
Hello guys and girls, I'm new here, sorry for bad english.
I just want to add 360 videos to youtube so i should use metadata but i cant open it. It always says samething. ''failed to execute script gui'' please help me..
I have Windows 7 ultimate SP1

**Comment by dcower** [comment]
Hi @shedie,

Apologies for the issue. Could you share what type of computer you have (32-bit or 64-bit)? You can find instructions here: [https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq](https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq)

If you have a 32-bit computer, you must follow [a different set of instructions](https://github.com/google/spatial-media/releases/tag/v2.0) currently, as the Metadata Injector only supports 64-bit Windows.

Dillon

**Comment by shedie** [comment]
Thanks for answering @dcower 
I have 64 bit computer. Here is the screenshot http://prntscr.com/blqphl

**Comment by dcower** [comment]
Hi @shedie, thanks for sharing! Could you also share a screenshot of the error message? In addition, could you ensure you're running the [latest Spatial Media Metadata Injector](https://github.com/google/spatial-media/releases/latest)? Thanks!

**Comment by shedie** [comment]
Thanks again @dcower 
I'll try to do it again, here is the screenshot about error http://prntscr.com/blqxs9

**Comment by shedie** [comment]
Now, i could open this http://prntscr.com/blr15l
But when i click ''open'' and i select a video, program closes.

**Comment by shedie** [comment]
Hello @dcower ? :)

**Comment by shedie** [comment]
Hi @dcower 
I still cant use it

**Comment by dcower** [comment]
Hi @shedie, are you running from the source? If so, could you try downloading the [Windows executable](https://github.com/google/spatial-media/releases/download/v2.0/360.Video.Metadata.Tool.win.zip) and let me know if that works? Thanks!

**Comment by shedie** [comment]
Hello @dcower 
It is still not working.
http://prntscr.com/bluhai

**Comment by dcower** [comment]
Hi @shedie, could you run Spatial Media Metadata Injector from the [command line](http://superuser.com/a/947000)? To do so, open a command line in the directory, then type "spa" and press Tab to autocomplete. Then press enter. Then please screenshot the command line output. Thanks, and sorry this is taking so long! :)

**Comment by shedie** [comment]
Hello @dcower 
Sorry I dont know how can i open the Spatial Media Metada Injector from the command line :(

**Comment by shedie** [comment]
Hello @dcower 
Is the command line is samething with cmd? My english isn't fine i think i didnt understand 
http://superuser.com/questions/946860/how-to-open-windows-cmd-so-that-it-starts-in-the-current-folder/947000#947000
this.

**Comment by shedie** [comment]
Hi @dcower 
I think I did something wrong.. http://prntscr.com/blvh5m

**Comment by shedie** [comment]
Hello @dcower 
Is that true? http://prntscr.com/blvl1a 
I have right clicked while pressing shift in the folder, and i have pressed tab, when i saw Spatial Media Metadata Injector i pressed enter. So this happened

**Comment by dcower** [comment]
Hi @shedie, it looks like you ran it correctly via the command line -- thanks! Unfortunately, it doesn't give me any additional info. Could you run the executable, `injector_debug_nonwindowed.exe`, from [injector_debug_nonwindowed.zip](https://github.com/google/spatial-media/files/336003/injector_debug_nonwindowed.zip) and screenshot any additional output? Thanks again for your patience and perseverance!

**Comment by shedie** [comment]
Hello @dcower 
I hope I did it correctly. Here is the screenshot. 
http://prntscr.com/blwujp

**Comment by shedie** [comment]
Hey @dcower  
Did i did sth wrong?

**Comment by shedie** [comment]
Hello @dcower 
I need help..

**Comment by dcower** [comment]
Hi @shedie, could you try this older Spatial Media Metadata Injector and let me know if it works: 
[360.Video.Metadata.Tool.win.oldUI.zip](https://github.com/google/spatial-media/files/337955/360.Video.Metadata.Tool.win.oldUI.zip)

Sorry again for the issue!

**Comment by shedie** [comment]
Hello @dcower 
I have this error now http://prntscr.com/bmahmu

**Comment by dcower** [comment]
@shedie: Sorry, I attached the wrong old version. :) Could you try this one instead: 
[360.Video.Metadata.Tool.win.evenolder_whoopsy.zip](https://github.com/google/spatial-media/files/337995/360.Video.Metadata.Tool.win.evenolder_whoopsy.zip)

**Comment by shedie** [comment]
Hello @dcower 
 I can open the program now and i can select a video but i cant select options :( http://prntscr.com/bmamzx

**Comment by dcower** [comment]
@shedie: Thanks for trying that -- good to know. Could you try moving the folder with all of the files to a path **without** non-[ASCII](http://www.asciitable.com/) letters? For example, you could move it to `C:\test\`.

**Comment by shedie** [comment]
@dcower What you mean with ascii letters? i did move to c:/test/ but still not working. What should i do ?

**Comment by dcower** [comment]
@shedie: Hmm, OK. Thanks for trying that. As a last resort, could you [create a new user](http://www.bleepingcomputer.com/tutorials/create-new-user-account-in-windows-vista-7/) called **test**, download the latest metadata injector to your Downloads folder, and try running it?

**Comment by shedie** [comment]
Hello @dcower
I have created new user and i can open it now but sometimes this window
opens but program doesnt work and sometimes this window opens and program
opens too http://prntscr.com/bmcezo


2016-06-29 1:23 GMT+03:00 Dillon Cower <notifications@github.com>:

**Comment by shedie** [comment]
@dcower  I could take this screenshot too http://prntscr.com/bmchza

**Comment by shedie** [comment]
@dcower  I cant open it now..

**Comment by shedie** [comment]
@dcower  I have changed my original user account's name, i still cant use it on my original account and ''test'' account. Only this window opens.. http://prntscr.com/bmcn6f

**Comment by dcower** [comment]
@shedie: Okay... time for a real last resort! Could you please follow the **Windows release notes** instructions here: https://github.com/google/spatial-media/releases/tag/v2.0

We believe that running from the source code should work in this case.

**Comment by shedie** [comment]
Hello @dcower 
I have tried to run it many times (like 10) and it opened just 1 time and i took screenshot 
http://prntscr.com/bmcvi3
But generally it doesnt open. :(

**Comment by shedie** [comment]
Hello @dcower 
I'll delete allthings and i'll redownload right sir? I hope it'll work. Thanks

**Comment by dcower** [comment]
@shedie: Sounds good to me. Hopefully it works this time! :)

**Comment by shedie** [comment]
@dcower And which user? test or my original user?

**Comment by dcower** [comment]
@shedie: Either user should work for this, but I would use `test` first to be sure.

**Comment by shedie** [comment]
@dcower  Okay sir! Thanks again :)

**Comment by dcower** [comment]
@shedie: No problem, sir. Really hope we can get this working!

**Comment by shedie** [comment]
@dcower  I have an error again...
http://prntscr.com/bmd25p
http://prntscr.com/bmd29d
http://prntscr.com/bmd2ce

**Comment by dcower** [comment]
@shedie: Hmm, could you try skipping that step in the instructions?

**Comment by shedie** [comment]
@dcower  without python2?

**Comment by dcower** [comment]
@shedie: Yes; start with **Download and extract the metadata injector source code.
**.

**Comment by shedie** [comment]
@dcower  I cant run ''gui'' because i havent python2 and i cant install it.

**Comment by dcower** [comment]
@shedie: Based on your [screenshot above](http://prnt.sc/blr15l), I think that you have Python installed on your other user account at least. Could you try that again, with the latest source code?

**Comment by shedie** [comment]
@dcower I have deleted all them.. And now i cant install it again..

**Comment by dcower** [comment]
@shedie: Oh no. :( Can you try installing Python to a different directory and see if that works?

**Comment by shedie** [comment]
@dcower  I have tried to install it to D:\ but it is still not loading 
http://prntscr.com/bmdcvh

**Comment by dcower** [comment]
@shedie: Could you try one of the portable Python distributions here: http://portablepython.com/ ?

**Comment by shedie** [comment]
@dcower I'm downloading Python(x,y) 2.7.10.0 808mb one now.
Sometimes I cant be sure about what i'm doing about because my english is not good enough :( 
Am I doing correctly now? Am I downloading true one?

**Comment by dcower** [comment]
@shedie: Yes, I'm hoping that that will work. I'm not entirely sure though. No worries about your English!

**Comment by shedie** [comment]
@dcower 
I installed! http://prntscr.com/bmdg7h
But only for this user.

**Comment by shedie** [comment]
@dcower Samething happened :(
http://prntscr.com/bmdiym 
Black window opens, metada doesnt :(

**Comment by shedie** [comment]
@dcower 
I have this error now
When I select the video I get this error
http://prntscr.com/bmdqj1

**Comment by suderman-google** [comment]
@shedie Would you be comfortable sharing the file so we can check whether the new issue is related to the file?

**Comment by shedie** [comment]
Hello @suderman-google 
I fixed the problem. I dont know what about it but i always get this error and i didnt care it i continued to 
inject the video so video worked! 
@dcower  Thank you so much! :D

**Comment by suderman-google** [comment]
@shedie if you are still comfortable sending us the file it could be helpful for us to see why the file initially failed and prevent future issues.

**Comment by shedie** [comment]
@suderman-google  I have some internet problems cause of Istanbul explosion. When it works normally again i'll upload the video file and send you link.

**Comment by shedie** [comment]
Hello @dcower @suderman-google 
I get this error http://prntscr.com/bsaksb and
here is the video http://www.mediafire.com/download/apf5anc824nspam/2016_07_13_11_13_03.mp4

**Comment by shedie** [comment]
I made a video about my problem I'll upload it to youtube and send link to here :D

**Comment by shedie** [comment]
Hello @dcower @suderman-google 
https://www.youtube.com/watch?v=Ndxy61uKvHQ&feature=youtu.be

**Comment by pwroberts** [comment]
Hi @shedie,

Thanks for sharing the Minecraft video you're trying to open.

According to the metadata inside the video, it was created with software called "Minecraft ReplayMod". There is a problem with the video's metadata, which could indicate a bug in Minecraft ReplayMod. I've explained the problem in detail below. I recommend you contact the developers of Minecraft ReplayMod and show them the information below.

There is a series of null bytes (0x0) at the end of the spherical video "uuid" atom, and because an unescaped null character is not a valid character in XML, the Python XML parser can't parse it. I think Minecraft ReplayMod might be computing the atom size incorrectly (16 bytes too large) and padding the atom with null bytes. Maybe it's double-counting the size of the UUID itself (16 bytes).

Here's the entire atom in hex, annotated:

```
; atom size: 472 bytes
00 00 01 D8
; atom name: "uuid"
75 75 69 64 
; spherical video UUID
FF CC 82 63 F8 55 4A 93 88 14 58 7A 02 52 1F DD
; spherical metadata XML: <?xml version="1.0"?> <rdf:SphericalVideo xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/"> <GSpherical:Spherical>true</GSpherical:Spherical> <GSpherical:Stitched>true</GSpherical:Stitched> <GSpherical:StitchingSoftware>Minecraft ReplayMod</GSpherical:StitchingSoftware> <GSpherical:ProjectionType>equirectangular</GSpherical:ProjectionType> </rdf:SphericalVideo>
3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 2E 30 22 3F 3E 20 3C 72 64 66 3A 53 70 68 65 72 69 63 61 6C 56 69 64 65 6F 20 78 6D 6C 6E 73 3A 72 64 66 3D 22 68 74 74 70 3A 2F 2F 77 77 77 2E 77 33 2E 6F 72 67 2F 31 39 39 39 2F 30 32 2F 32 32 2D 72 64 66 2D 73 79 6E 74 61 78 2D 6E 73 23 22 20 78 6D 6C 6E 73 3A 47 53 70 68 65 72 69 63 61 6C 3D 22 68 74 74 70 3A 2F 2F 6E 73 2E 67 6F 6F 67 6C 65 2E 63 6F 6D 2F 76 69 64 65 6F 73 2F 31 2E 30 2F 73 70 68 65 72 69 63 61 6C 2F 22 3E 20 3C 47 53 70 68 65 72 69 63 61 6C 3A 53 70 68 65 72 69 63 61 6C 3E 74 72 75 65 3C 2F 47 53 70 68 65 72 69 63 61 6C 3A 53 70 68 65 72 69 63 61 6C 3E 20 3C 47 53 70 68 65 72 69 63 61 6C 3A 53 74 69 74 63 68 65 64 3E 74 72 75 65 3C 2F 47 53 70 68 65 72 69 63 61 6C 3A 53 74 69 74 63 68 65 64 3E 20 3C 47 53 70 68 65 72 69 63 61 6C 3A 53 74 69 74 63 68 69 6E 67 53 6F 66 74 77 61 72 65 3E 4D 69 6E 65 63 72 61 66 74 20 52 65 70 6C 61 79 4D 6F 64 3C 2F 47 53 70 68 65 72 69 63 61 6C 3A 53 74 69 74 63 68 69 6E 67 53 6F 66 74 77 61 72 65 3E 20 3C 47 53 70 68 65 72 69 63 61 6C 3A 50 72 6F 6A 65 63 74 69 6F 6E 54 79 70 65 3E 65 71 75 69 72 65 63 74 61 6E 67 75 6C 61 72 3C 2F 47 53 70 68 65 72 69 63 61 6C 3A 50 72 6F 6A 65 63 74 69 6F 6E 54 79 70 65 3E 20 3C 2F 72 64 66 3A 53 70 68 65 72 69 63 61 6C 56 69 64 65 6F 3E
; (Atom should probably end here after 456 bytes, but because size=472, we keep reading)
; 16 null bytes - invalid XML!
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

By the way, since your video already contains spherical metadata, you can upload it to YouTube without using the metadata injector. (YouTube seems to handle the invalid XML OK.)

Thanks,

Paul
