### ISSUE TITLE
Does not properly handle Ricoh Theta video

### ISSUE THREAD

**Issue by triune** [google/spatial-media#107]
Here is the video before injection : https://youtu.be/xt--U6OWEiE
And here is the video after injection: https://youtu.be/zNEP5KmvAb4

The 3D stitching is not working correctly.

**Comment by dcower** [comment]
Hi @triune,

Cool video! You first need to "stitch" the video using the [Ricoh Theta Basic app](https://theta360.com/en/support/download/). I believe the app injects metadata as well, so it should be good for upload to YouTube then. Here's an article that talks more about this: [https://theta360.com/en/support/manual/m15/content/pc/pc_05.html](https://theta360.com/en/support/manual/m15/content/pc/pc_05.html)

**Comment by triune** [comment]
@dcower thanks for the advice! I actually only have access to Linux (Ubuntu, ChromeOS, Android) machines so I was hoping to do this somehow outside of having to track down a Mac or Windows box. It is pretty silly that the Android app cannot perform the stitching itself. That seems like a very rudimentary feature. The link that brought me here from the YT help site gave me a glimmer of hope that there would be some way to do this programmatically on Linux somehow. Any idea if something like ffmpeg can do this itself? I get the feeling this might be a better question for the Ricoh forums ;)

**Comment by dcower** [comment]
@triune: No problem! Hmm, it seems like the best route might be trying to run Ricoh's software in a VM, but I haven't tried that myself. I found a [couple](http://theta360.guide/community-document/community.html#_linux) [pages](https://developers.theta360.com/en/forums/viewtopic.php?f=4&t=36) that seem hopeful.

Depending on how much work you want to put in, adding an ffmpeg filter (example here: https://github.com/facebook/transform) might not be _tooooo_ difficult. ;) Let me know if you find a solution though!

**Comment by triune** [comment]
Oh wow, nice! I haven't used WINE in ages. That might just be the thing that's the easiest to do! I fear coding a filter in C since I haven't touched that language since my Comp Sci 400 class (O_o) ... will keep ya posted 🎱

**Comment by rengelmann** [comment]
This is the 'raw' dual fish eye projection needs to be converted to equirectangular. The workflow with the iOS app is to download the movie from the camera within the Theta app and it will convert, and then move the resulting video to wherever (YouTube, FB, etc). If you just transfer from the camera directly over usb it won't do the conversion. Can't verify this is the process with the Android app, but it should be.

**Comment by triune** [comment]
The Android app can play the dual fish eye video in several different views: standard, vr single, vr twin and export to facebook and or any other service via the Android share dialog. The share method seems broken currently in that I can't select a time range to export the video. So, apparently I can't export the video to YT from the Android app.

Per https://hackaday.io/project/5077-metaverse-lab/log/30947-ricoh-theta-s-360-streaming I can't use WINE to run the Theta App either because it only works on images under WINE.

"Linux users running the program through Wine will be disappointed as the it fails to convert video or do real-time stitching for streaming into equirectangular format. The lens geometry for the THETA is based on equidistant projection. RICOH does not make detailed lens parameter information available. This is also known as lens distortion data. Developers often ask for this information to improve stitching. It is proprietary and not available as of December 2015. However, stitching is still possible without this information."

So, I spent some time setting up an OSX VM and got the app running there instead... which stitches quite nicely:

https://www.youtube.com/watch?v=UvBlk5fRDtM

But, apparently YT still doesn't see the video as 360 and I have to run the injection tool here again afterwards... and you would think that was it, but nope, spatial-media injected format is still not 360 on YT : https://www.youtube.com/watch?v=mS9-6SDh7Dw

**Comment by pwroberts** [comment]
Hey @triune,

Glad you got the stitching app running!

Unfortunately, when you upload a 360 video, it can take a little extra time for YouTube to process the 360 metadata, even after initial "processing" is complete. Confusing, I know! Both of your latest YouTube links (https://www.youtube.com/watch?v=UvBlk5fRDtM and are rendering correctly as 360 videos for me, at least on desktop web and iOS. Are they working for you now?

Thanks,

Paul

**Comment by triune** [comment]
@pwroberts yes, that is definitely confusing... processing done to me meant that's all YT is gonna do on those videos. Perhaps they should work on correctly reporting that information some how. Yes, I can see both videos correctly in 360 now. I guess the spatial-media step is unnecessary after stitching in the app. 

Thanks for all the help here!
//G
