### ISSUE TITLE
360 video metadata ERROR "Failed to execute script gui"

### ISSUE THREAD

**Issue by Luca000** [google/spatial-media#108]
Hello, i've recorded a 360 video using samsung gear 360.
Using the instructions in this video https://www.youtube.com/watch?v=-zPTl_YXCIU
i stitched it on my pc using gear 360 actiondirector, but at some point after stitching the video it requires me to use 360 video metadata. Problem is, after downloading and extracting it in a folder, everytime i try to open it to inject the metadata it won't open at all and show a little window saying "fatal error, failed to execute script gui"
im working on a 64 bit windows system (NOT 10). Can someone please help? I'm not an expert into this kind of stuff, so please if possible tell me step to step how to solve this...

**Comment by dcower** [comment]
Hi @Luca000, thanks for reporting the issue. Could you run `injector_debug_nonwindowed.exe` from [injector_debug_nonwindowed.zip](https://github.com/google/spatial-media/files/336003/injector_debug_nonwindowed.zip) using the [command line](http://superuser.com/a/947000), and screenshot any additional output? This will give us more information that will hopefully help us figure out the issue. Thanks!

**Comment by Luca000** [comment]
Hi @dcower , thanks for the answer. Unfortunately, i downloaded from the link you gave me and as soon as i double click the application it pops up the black window and then shuts down in 2 seconds. I don't even have the time to write the command you gave me..
Anything else I can do?

**Comment by suderman-google** [comment]
Hey Luca000, I'll give you a hand.

To open the application you will need to open a command line and you can follow [these instructions](http://www.digitalcitizen.life/7-ways-launch-command-prompt-windows-7-windows-8). Once you have a command line open, drag the [executable](https://github.com/google/spatial-media/files/336003/injector_debug_nonwindowed.zip) into the command line and press enter. This should let you see what is in the window. After, screenshot the output and we will see what we can do.

**Comment by Luca000** [comment]
![screen](https://cloud.githubusercontent.com/assets/20186257/16516849/b809ca7c-3f7a-11e6-88d2-f6ff261427fe.PNG)

Done, here's the resulting screenshot ^^
Thank you for now :)

**Comment by suderman-google** [comment]
Hey Luca000,

I think we should have a work around for you.

1. Install [python](https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi).
2. Download this [zip file](https://github.com/google/spatial-media/archive/v2.0.zip) with the metdata injector.
3. Extract the zip file with winrar.
4. Double click on the gui.py in the folder.

Could you see how that works for you?

**Comment by Luca000** [comment]
Good morning @suderman-google, 
it worked perfectly and the program opened on the first try! 
Thank you a thousand times ^^ And obviously thanks to @dcower too :D

**Comment by suderman-google** [comment]
Great to hear the work around was successful.
