### ISSUE TITLE
Does not properly handle LG360 cam video

### ISSUE THREAD

**Issue by BradTwining** [google/spatial-media#111]
I have been able to use Spatial Media Metadata Injector and upload it to YouTube. It unfortunately uploads it with the two circles of the two lens side by side and when it is processed you can navigate it with 360 but the stitching is not right, See link to video here. 

https://youtu.be/vVArDJLq3P4

Someone had a similar issue with the Ricoh Theta and they had to have the original file in a flat rectangular file rather than two circles side by side. Anyway can you please help me? I am already frustrated with the limitations in the LG's lack of sharing ability with Facebook etc. 

Thanks

**Comment by VincentGuigui** [comment]
LG and Ricoh cameras require using their own stitching software before sharing. Those will convert the "two-circles" file into a wide panorama (equirectangular) which in turn can be use with the Spatial Metadata injector.

Spatial Metadata Injector is not a stitching software, it just injecting some metadata to tell YouTube how to handle the 360/3D video.

Maybe one day, YouTube will handle "two-circles" files directly

**Comment by BradTwining** [comment]
Vincent, thanks for your reply. You are right, and the issue is that when I transfer the videos straight from the SD card to the computer is comes across as two circles. But when I download it first to my phone from the camera then it converts to the needed equirectangualr projection. OK, so it looks like I will download everything onto my iphone, then transfer it this way to my computer and then inject it with the metadata, then upload. It should work, I will get back to you with how it goes. Will it be simplified one day?

**Comment by BradTwining** [comment]
All good Vincent, thanks for your help. Here is the link to the fixed 360 video

https://youtu.be/fWxSxkBEGyw

**Comment by dcower** [comment]
Cheers for the quick answer, @VincentGuigui! And nice video, @BradTwining; can't wait for the next episode of _Animal Attacks 360 Camera_.

I'll have to see if my cat is willing to participate...
