### ISSUE TITLE
HOA capability

### ISSUE THREAD

**Issue by killwasi** [google/spatial-media#112]
I would like to know what is the YouTube capability in terms of ambisonic order.
Can I embed e.g. 25 channel audio into mp4 file via Your script and successfully play it on YouTube? Or is it only restricted to 4-channel 1st order?

**Comment by dcower** [comment]
Hi @killwasi,

Currently, YouTube only accepts 1st-order ambisonic uploads (4 channel). See [this page](https://support.google.com/youtube/answer/6395969?hl=en) for more information.

Thanks,
Dillon

**Comment by dcower** [comment]
Hi @killwasi,

Sorry for the delay here. Agreed that minimum requirements is a bit ambiguous -- we'll look into getting that fixed.

I can't share any specific timelines, but I can say that we are working on higher-order ambisonic compression using the Opus codec. Hold tight! :)

Dillon
