### ISSUE TITLE
Clarify the location of the sv3d & st3d boxes in spherical-video-v2 spec.

### ISSUE THREAD

**Issue by acolwell** [google/spatial-media#115]
The current spec indicates that sv3d & st3d boxes container is a "Video Sample Description". I think this should be changed to VisualSampleEntry since that is the name used in the ISOBMFF spec. I also think it would be good to clarify the box placement by saying something like "These boxes must come after other boxes from derived specifications and before optional boxes at the end of the VisualSampleEntry definition such as the CleanApertureBox and PixelAspectRatioBox." I think this would make it clear that these boxes are intended to be after standard avc1 specific boxes in a VisualSampleEntry and before the optional VisualSampleEntry boxes.

**Comment by acolwell** [comment]
I also just realized that the example at the bottom should also be updated to reflect this recommendation.

**Comment by dcower** [comment]
Fixed via #121.
