### ISSUE TITLE
Spatial Audio Tag greyed out

### ISSUE THREAD

**Issue by fakelovestuff** [google/spatial-media#116]
Hello,
I am unable to click on the 'My video has spatial audio (ambiX ACN/SN3D format) tab'. I used the ambiX converter plugin in reaper to export a 4channel audio wave file. Then I took that file and married to a video in adobe premiere. I export an mp4 from there with AAC audio format and I tried both mono and stereo. I then take my mp4 and try converting it with your app. It allows me to check all other boxes except for the one mentioned previously. Any ideas would be greatly appreciated. Thanks so much.

**Comment by dcower** [comment]
Hi @fakelovestuff, could you have a look at the section on **Exporting** in this guide: https://support.google.com/jump/answer/6400185?hl=en&ref_topic=6399805

To export video with spatial audio from Premiere, you have two options:
1. Export using the QuickTime format with uncompressed 4-channel audio.
2. Export video and audio separately and combine using iFFmpeg or similar.

Hope this helps!
Dillon
