### ISSUE TITLE
Youtube uploading issue

### ISSUE THREAD

**Issue by HubiWiWi** [google/spatial-media#117]
Hello,

I have a serious issue when I try uploading my 360 video with Ambix Sound.
The file specs are : 1920x1080, 30 fps, H.264, 4 channel Ambix 48kHz 24 bit, .mov container.

Everytime I try to upload on YouTube my video, it crashes after uploading, during processing step. It gets stuck at 0% and then I get a Youtube error message.

**BUT**, if I don't inject metadata with your Spatial Media Metadata Injector (I have the latest version), and if I try to upload the video without metadata, it is uploaded and processed well !

Your help would be much appreciated since I really need to upload my work soon.

Thank you

**Comment by dcower** [comment]
Hey @HubiWiWi,

Sorry you're encountering this issue. Could you share how you created the .mov file with ambisonic audio? I believe the issue here may be that the channel layout of the audio is "quad" when it must be "4.0" or unspecified. Knowing how you created the file should let us figure out a solution.

Thanks,
Dillon

**Comment by HubiWiWi** [comment]
Hi Dillon,

Thanks for your REALLY fast answer ! 👍 
Here what I did :

I exported a 8 channel wav file after mixing with the FB360 Engine (in Pro Tools). I encoded this file as B-Format Ambix/Youtube with their encoder.
Then I merged video and audio thanks to FFMpeg with this command : 
ffmpeg -i video.mov              \
       -i sound.wav \
       -channel_layout 4.0                           \
       -c:v copy -c:a copy videoandsound.mov

And then I injected the metadata.

**Comment by dcower** [comment]
Ah! Thanks for sharing. Could you try following this guide from the FB360 Spatial Workstation docs: [Add Spatial Audio to a Video For YouTube](https://fb360spatialworkstation.zendesk.com/hc/en-us/articles/207888189-Add-Spatial-Audio-to-a-Video-For-YouTube) ... and let me know if it works then?

**Comment by HubiWiWi** [comment]
Works like a charm !
Thanks a lot !

**Comment by dcower** [comment]
No problem! Glad it worked out. :)
