### ISSUE TITLE
Kodak PixPro SP360 conversion to YouTube format does not work.

### ISSUE THREAD

**Issue by aNeutrino** [google/spatial-media#122]
Hi Spatial media team :)
I wanted to use your software for preparation before uploading to YouTube my 360 degrees videos made by KODAK pixpro SP360 camera.
Unfortunately after using your software, videos are not looking good :(

Below you can find a links to videos Before and After using your software.
[YouTube lint to: original video](https://www.youtube.com/watch?v=DkJ8IoDMfsA)
[YouTube lint to: video after using script](https://www.youtube.com/watch?v=RYLg9XEJ45I)

I used very small sample video, only 2 seconds and 2.5MB
[the original mp4 file from camera, with this video you can also download here](http://upload.aleph.engineering/uploads/2.5MB_oryginal.mp4)

I am Linux user and software provided by KODAK runs only on windows, and seems to be very CLICK ONLY, no scripting/command line mode anyway. As I have 4TB (terabytes) videos made during my 3 months trip in Cuba I would need automatic way of converting and uploading my videos to YouTube.

I would be very happy if you could tell me how to make my videos viewable in YouTube 360player.

regards
aNeutrino

EDIT:
I believe that the problem is about the format of original video.
it is called: `"Little Planet"`
and the format your software is injecting is `equirectangular`:

```
spatialmedia/metadata_utils.py
50:    "<GSpherical:ProjectionType>equirectangular</GSpherical:ProjectionType>
```

**Comment by dcower** [comment]
Hi @aNeutrino,

Before uploading to YouTube (and before injecting metadata), you'll need to import the video into [Kodak's software](http://kodakpixpro.com/Europe/support/downloads.php) to convert the video into an equirectangular projection. (YouTube only supports 360 videos using an equirectangular projection.)

It might be possible to run via WINE... I'm not sure. You might also give [Autopano](http://www.kolor.com/wiki-en/action/view/Installing_on_Ubuntu_GNU/Linux_from_the_.tar.gz_file) a shot -- I believe there are tutorials on YouTube.

Best of luck!
Dillon
