### ISSUE TITLE
Spatial audio on Firefox Browser

### ISSUE THREAD

**Issue by HubiWiWi** [google/spatial-media#123]
Hello,

I uploaded a few days ago a 3D video with spatial audio on YouTube.
Everything seems to work fine on Chrome. But I checked this morning on Firefox (latest version on Mavericks and Yosemite) and the mix is a complete mess comparing to Chrome. 
The spatial image is not the same, the movement of the audio sources are really weird on Firefox, and the thing which should be at the center are not at all.

Is the processing supposed to be the same on each browser ?

Thank you for your answer.

**Comment by yingster-** [comment]
Hi

Spatial audio on YouTube should support FF.
Would you mind share the following so I can check?
a) Is it still broken? There was a FF bug in FF<47, but versions >=47 should work.
b) If it's still broken, would you mind include the URL to your video?
c) How is it broken? Does audio rotate at all? Try something like [youtu.be/mJWodsZclP4](youtu.be/mJWodsZclP4) which has a single audio source.
d) Right click on the player and select copy debug info. Please include it to help the debugging process. 

Thanks!

**Comment by acolwell** [comment]
closing because this is old and there didn't appear to be a response to the questions posed.
