### ISSUE TITLE
Meta Data Injector wont install

### ISSUE THREAD

**Issue by sniper22b** [google/spatial-media#124]
Hi,

Having an issue when installing meta data injector, I have attached an image of the issue I have when installing.  I am running Windows 64bit

Any ideas?

Thanks.

![issue](https://cloud.githubusercontent.com/assets/20972478/17592362/ef3c0814-5fd9-11e6-994d-b43002621b68.png)

**Comment by Roadkitten** [comment]
![](https://cloud.githubusercontent.com/assets/20972478/17592362/ef3c0814-5fd9-11e6-994d-b43002621b68.png)

**Comment by acolwell** [comment]
Appears to be the same issue as #142
