### ISSUE TITLE
Support for 180 degree equirectangular video

### ISSUE THREAD

**Issue by orkunkilinc** [google/spatial-media#126]
Hi spatial-media team and other contributers,

I am trying to get youtube to display my 180 degree equirectangular video properly but even changing the paramters such as

FullPanoWidthPixels  
FullPanoHeightPixels  
CroppedAreaImageWidthPixels  
CroppedAreaImageHeightPixels

to trick youtube to warp it properly but unfortuantely that does not work.

I'm begnning to think that Youtube does not support this but even my efforts to go around this and trick Youtube to do this failed.

Only solution I have come up with is adding black padding around the video so that real video is represented in half of the video(180 degrees) but this is highly CPU intensive and not ideal.

If you have any ideas or possible solutions I would be really happy to hear them.

Thanks!

**Comment by suderman-google** [comment]
Hey Orkun,

Unfortunately YouTube does not support cropped 360 videos so to upload your video you will need to add the black bars you mentioned. Sorry we can not be of more help.

**Comment by dcower** [comment]
Hi there,

YouTube does not support changing FullPanoWidthPixels/FullPanoHeightPixels/CroppedAreaImageWidthPixels/CroppedAreaImageHeightPixels from their default values.

Going forward, we are considering support in the [Spherical Video v2 RFC](https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md) and YouTube for a mechanism that would allow this. Could you specify exactly what you're looking for? E.g., do you need lens distortion accounted for?

Thanks,
Dillon

**Comment by orkunkilinc** [comment]
Hi Dillon,

I am using a camera with fisheye lens mounted on the wall with practical view of 180 degrees. So some crude fisheye distortion correction would be awesome. Since it is wall mounted the image consists of 180 degrees horizontal view.

Actually KRpano does everything I want and I can tweak dewarping by changing hFov and vFov but since iOS and safari has problems with WebGL, playing video and dewarping it on-the-fly makes it really laggy on iphone's and ipad's. Thus I think a native solution is needed.

Do you guys can give me any information about when  Spherical Video v2 RFC will be implemented in YouTube?

Also I am willing to help as far as in me lies to make this process go faster.

Thanks,
Orkun

**Comment by zougloub** [comment]
Hi again @jamiesonpepper issue is closed as completed after 8 years, I lost track... maybe add a closing statement? Thanks!

**Comment by jamiesonpepper** [comment]
Hello @zougloub! I am fairly certain YouTube supports this now with VR180. Here is an unlisted sample I took with a Kodak Pixpro VR180 and exported in Equirectangular format, injected the metadata and uploaded to YouTube without any further edits. As this hadn't been updated in years I was doing some issue clean-up to only continue to maintain updates for newer releases of Python but hopefully the additional context helps!

https://www.youtube.com/watch?v=KxfcPyyg8DM
