### ISSUE TITLE
Trying to add metadata fails

### ISSUE THREAD

**Issue by ubusound** [google/spatial-media#129]
Hi,

I have the Kodak PixPro 4k, and just received my TetraMic.  I've converted the recording to "YouTube" standard with the Blue Ripple Decoder plug in and reaper.

I exported a video in the Kodak software to Youtube format, opened it in Quicktime 7 Pro, deleted the embedded audio track, and added the B-Format track, saving it as an .mov file.

When I upload the file itself, YouTube does not recognize it as a 360 video.  When I try running spatial-media on it, I get:

`Jeremys-Mac-Pro:spatial-media-master jeremylee$ python spatialmedia -i --spatial-audio /Volumes/Storage/SP360\ 4k/Youtube\ Exports\ from\ PixPro/Oregon\ Beach\ Youtube\ w-\ B-Format\ Audio.mov /Volumes/Storage/SP360\ 4k/Youtube\ Exports\ from\ PixPro/Oregon\ Beach\ Youtube\ w-\ B-Format\ Audio-metadata.mov
Processing: /Volumes/Storage/SP360 4k/Youtube Exports from PixPro/Oregon Beach Youtube w- B-Format Audio.mov

Error, invalid size 0 in ? at 21371

Error, failed to load box.

Error, failed to load box.

Error, failed to load box.

Error, failed to load box.

Error, failed to load .mp4 file.

Error file could not be opened.

Traceback (most recent call last):

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals

  File "/Users/jeremylee/Box Sync/ Transfer to Mac Pro/Ambisonics Stuff/spatial-media-master/spatialmedia/**main**.py", line 111, in <module>
    main()

  File "/Users/jeremylee/Box Sync/ Transfer to Mac Pro/Ambisonics Stuff/spatial-media-master/spatialmedia/**main**.py", line 96, in main
    console)

  File "/Users/jeremylee/Box Sync/ Transfer to Mac Pro/Ambisonics Stuff/spatial-media-master/spatialmedia/../spatialmedia/metadata_utils.py", line 417, in inject_metadata
    inject_mpeg4(infile, outfile, metadata, console)

  File "/Users/jeremylee/Box Sync/ Transfer to Mac Pro/Ambisonics Stuff/spatial-media-master/spatialmedia/../spatialmedia/metadata_utils.py", line 359, in inject_mpeg4
    if not mpeg4_add_spherical(mpeg4_file, in_fh, metadata.video):

  File "/Users/jeremylee/Box Sync/ Transfer to Mac Pro/Ambisonics Stuff/spatial-media-master/spatialmedia/../spatialmedia/metadata_utils.py", line 146, in mpeg4_add_spherical
    for element in mpeg4_file.moov_box.contents:

AttributeError: 'NoneType' object has no attribute 'moov_box'

Jeremys-Mac-Pro:spatial-media-master jeremylee$ python spatialmedia /Volumes/Storage/SP360\ 4k/Youtube\ Exports\ from\ PixPro/Oregon\ Beach\ Youtube\ w-\ B-Format\ Audio.mov 
Processing: /Volumes/Storage/SP360 4k/Youtube Exports from PixPro/Oregon Beach Youtube w- B-Format Audio.mov

Error, invalid size 0 in ? at 21371

Error, failed to load box.

Error, failed to load box.

Error, failed to load box.

Error, failed to load box.

Error, failed to load .mp4 file.

Error, file could not be opened.`

Any idea what I'm doing wrong?  I'm new to this workflow.

Thanks!

Jeremy

**Comment by suderman-google** [comment]
Hey Ubusound,

Sorry for the delay. I believe Quicktime 7 may not remuxed the audio / video together correctly resulting in an invalid final file. Could you try combining your ambisonic audio with your video using iFFMpeg?

http://www.iffmpeg.com/

**Comment by ubusound** [comment]
Cool- I'll give it a shot!  I wasn't aware that FFMpeg had a GUI.  For me, the less command line, the better!

**Comment by ubusound** [comment]
OK.  So adding the track through iFFMPEG led to the VIDEO being recognized as 360º, but the audio is not, even after running the python script.  Here's the output from the script:

Processing: /Volumes/Storage/Movies/Oregon Beach.mov
Saved file settings
	Track 0
		Spherical = true
		Stitched = true
		StitchingSoftware = Spherical Metadata Tool
		ProjectionType = equirectangular
	Track 1
		Ambisonic Type: periphonic
		Ambisonic Order: 1
		Ambisonic Channel Ordering: ACN
		Ambisonic Normalization: SN3D
		Number of Channels: 4
		Channel Map: [0, 1, 2, 3]

And I followed the instructions here:

https://fb360spatialworkstation.zendesk.com/hc/en-us/articles/207888189-Add-Spatial-Audio-to-a-Video-For-YouTube

Is there something I'm doing wrong?  Obviously there is ;-).  I'm giving YouTube a B-Format 24bit 48k audio file to play with, but even after the metadata injection, it's just playing back in stereo- not panning around with the video in Firefox.

Thanks for any more help you can give!

Jeremy

**Comment by ubusound** [comment]
Ah. Silly me. It looks like the only platform to support ambisonic playback is Android. Maybe my uploads did work after all. The 360 video works on OSX and iOS, and I assumed that audio had the same requirements. 

Guess I have to borrow an android something to see if it's working. What are the requirements on android for ambisonic playback? When will it be implemented on other devices?

Thanks!

**Comment by dcower** [comment]
Hey @ubusound,

Sorry for any confusion here! Ambisonic audio playback should work today on web (Chrome) as well as Android; so hopefully you won't have to borrow an Android device. :)

We're actively working on bringing it to more platforms, but I can't share any timelines there.

Dillon

**Comment by ubusound** [comment]
Ah- I'll try Chrome. It didn't work in FireFox or Safari.  I'll give that a shot.

Thanks!!

**Comment by ubusound** [comment]
It worked!  It seems to take YouTube FOREVER to process the ambisonic audio.  My 90 minute video took maybe a day and a half to play back binaurally, but it works!  Is there any way that the YouTube website could give us feedback not only when a video is available for viewing, but when it's actually done processing?
