### ISSUE TITLE
problem when posting video on Facebook

### ISSUE THREAD

**Issue by Marfn123** [google/spatial-media#134]
Always use the Spatial Media Metadata Injector to insert metadata in the video to post on facebook and youtube. However today stopped working on facebook, to post the video he normal, that is not is 360. Since youtube is working properly.

It happened some updating that facebook does not accept more such metadata?

**Comment by tomtomtong** [comment]
I also meet this issue. Hope FB could fix it asap.

**Comment by evanmang** [comment]
you can use Facebook's own injector, part of the spatial audio workstation. i used it yesterday and it works great

**Comment by Marfn123** [comment]
Link please?

**Comment by evanmang** [comment]
[](https://facebook360.fb.com/spatial-workstation/)

**Comment by SahilMadan** [comment]
Thanks for the notification. We're currently looking into the issue and will keep you updated.

**Comment by intellectualamoeba** [comment]
@Marfn123 the issue should have been fixed quite some time back. As @evanmang pointed out, do feel free to use the FB360 Encoder app for muxing purposes as well, but metadata injected with the spatial media injector is supported off the bat as well (As long as you adhere to the container specs for Fb). Feel free to post directly in the Spatial Workstation group on Facebook (https://www.facebook.com/groups/1812020965695437/) if it still doesn't work for you. Happy to help!

**Comment by MethexisStudios** [comment]
Can the Spatial workstation encoder work without sound? I am trying to inject metadata to a 360 panoramic video with no sound and I can't. Is it necessary to have sound ?

**Comment by intellectualamoeba** [comment]
> Hey sorry for bumping such an old issue but i've been using the encoding fine for years and it still works. However whenever I try to post the same video that works on YouTube, Facebook doesn't read the metadata when posting into a group chat in Messenger (works fine in regular groups). Anyone got any ideas?

I am no longer working at the company so may not have the most up to details here - but I don't think group chat/messenger threads have the same level of decoding support that posting into Watch or Feed (or Oculus Media Studio) have. Sorry, that's the most up to date issue I have. You can quickly verify by posting the same video as a secret post on your Page or profile on News Feed, see if it works and then checking on messenger.
