### ISSUE TITLE
How to inject metadata into 360 video for platform of iOS and Android?

### ISSUE THREAD

**Issue by cievon** [google/spatial-media#135]
As title, on iOS、Android platform, how to inject metadata into 360 video in order to upload to youtube, ths

**Comment by SahilMadan** [comment]
Hi cievon,

The spatial-media tools aren't supported on iOS. Your best bet would be to use the spatial-media tools on a desktop machine.

**Comment by cievon** [comment]
I have make a c++ port is used to inject metadata into 360 video on iOS and Android based on VaroOkan,https://github.com/cievon/spatial-media/tree/master/spatialmedia

**Comment by mdaymard** [comment]
Hello, I'm still also searching for a way to do this on Android. I've tried with ffmpeg without success.
Thanks cievon  for the C++ port for Android ! By any chance do you still have the library and the JNI classes for your fork to be usable with Java ? Thanks in advance

**Comment by tomtomtong** [comment]
I finally use Lightweighted PythonistaKit framework to achieve this. My github code is posted below.
https://github.com/spincle/Spatial-Media-For-iOS
