### ISSUE TITLE
stretching 360x180 degree spherical videos

### ISSUE THREAD

**Issue by ghost** [google/spatial-media#136]
Hi, pulling my hair out at the minute with all this but google says to use this program to inject spherical videos for 360 degree playback in you tube...however when in youtube it stretches it as though its treating it as a 360x360 degree sphere 
heres an example: https://www.youtube.com/watch?v=yzlzuhRjVfc
its driving me a little nuts trying to find a solution to this for uploading 360x180 degree vids (the default software does it sort of but the video it makes is Equirectangular, its also uneditable and really low volume example here: https://www.youtube.com/watch?v=OAbJciN_qXA ) and trying to convert that video to one thats editable with the audio gain up then wont display in youtube correctly : see https://www.youtube.com/watch?v=E9Qa7eKecoQ 
I swear i am going to have two bald patches either side of my head if i cant solve this soon lol
In theory your program should take that spherical mp4 (360 degree by 180 degree) and make it so google plays it correctly yes? if so this is a bug if its looking for a 360x360 sphere then please make this a feature request (with the abundance of cheap 360x180 degree cameras its something that is likely to be a major issue sooner then later either way)

**Comment by AndrewHazelden** [comment]
Hi. Your video is in a fisheye format. You have to stitch it using another tool into an equirectangular projection before it can be used with YouTube 360.

**Comment by mrgreaper** [comment]
Stitch it? Don't fully understand, the only results I could find seem to
talk about stitching two camera views together to make 360x360 this
ofcourse is not the case with a single camera, though the third video I
linked is definitely not in fish eye

**Comment by sphericvr** [comment]
@mrgreaper Your second video (https://www.youtube.com/watch?v=OAbJciN_qXA) is the correct way to upload, you would need to use a video editing software to change the focus point. Your camera is pointing up in that video. If you point the camera horizontally you should be able to edit it to upload as a half sphere.
![wrong](https://cloud.githubusercontent.com/assets/11526559/19899584/101b7798-a037-11e6-9767-a1d668f947c1.jpg)
![right](https://cloud.githubusercontent.com/assets/11526559/19899585/101d52f2-a037-11e6-82e3-d695d03f38c5.jpg)

**Comment by sphericvr** [comment]
Also, as a correction to your previous post, 360 video is 360x180, what you need to upload is a 180x180 aspect ratio centered in a 360x180 ratio video.

**Comment by mrgreaper** [comment]
Sadly that is from the cameras app, and uses some wierd codes that can not
be edited, the third video is a converted version of that video, which
YouTube then does not like.
The intended function will be to record a tabletop game weekly, so the
camera will be above the table recording the table and all participants (so
the ceiling which it can't record should be irrelevant to all but the most
weirdest of viewers who will forever debate "plastered" or "artexed")
So here's the question, what do I need to do to the second video to make
YouTube see it as a 360 video like the second video?

**Comment by sphericvr** [comment]
In premiere or another video editing software, cut your video in half and rotate, export and inject: 
![right2](https://cloud.githubusercontent.com/assets/11526559/19902251/59439d98-a040-11e6-9576-11dd4e7cc3c9.jpg)

**Comment by mrgreaper** [comment]
Ah cool, I'll grab premiere after work (assuming free, if not I'll find an
alternative) and give it a try thank you

**Comment by Bnaya** [comment]
I'm having the same issue with 220x360 video
The camera is some generic Chinese generic thing called pano view
