### ISSUE TITLE
Metadata Injector Won't Install

### ISSUE THREAD

**Issue by mmosier1** [google/spatial-media#137]
When I execute the .exe on my Windows 7 machine all I get are some DOS windows showing extracts and then they close. That's it. Can someone tell me what I'm doing wrong?

Thanks

mm

**Comment by SahilMadan** [comment]
Hi mm,

Could you try the following: Open up CMD in the current directory and try executing the .exe through CMD/Powershell. That should give you some output and give you a chance to read it, without closing the DOS window.

**Comment by mmosier1** [comment]
Thank you... I've found a solution that bypasses the need for this.

mm

**Comment by trax2** [comment]
I have the same problem can you tell me your solution?
thanks
