### ISSUE TITLE
YouTube Unsupported File Type

### ISSUE THREAD

**Issue by M2Dr2** [google/spatial-media#138]
I keep getting my 360 video and spatial audio file rejected by YouTube when trying to upload. I have used the following code when working with ffmpeg:

ffmpeg -loop 1 -i R0010183.jpg -i Location1B.wav -map 1:a -map 0:v -c:a copy -channel_layout quad -c:v libx264 -vf scale=iw:ih*1.125 -pix_fmt yuv420p -b:v 40000k -bufsize 40000k -shortest Location1.mov

The image was taken with a Ricoh Theta camera and i've ensured my audio is set to ambiX ACN/SN3D format. I've injected the metadata using the Spatial Media Metadata Injector:

Saved file settings
	Track 0
		Ambisonic Type: periphonic
		Ambisonic Order: 1
		Ambisonic Channel Ordering: ACN
		Ambisonic Normalization: SN3D
		Number of Channels: 4
		Channel Map: [0, 1, 2, 3]
	Track 1
		Spherical = true
		Stitched = true
		StitchingSoftware = Spherical Metadata Tool
		ProjectionType = equirectangular

The frustrating thing is that a colleague of mine has had success using the same files and the same process. I am now at a loss as to how to solve the issue.

I would appreciate any advice or comments,
Mark

**Comment by dcower** [comment]
Hey Mark,

The issue here is the `channel_layout` flag passed to ffmpeg; for upload to YouTube, your file's audio must use the `4.0` channel layout (or be unspecified). So your ffmpeg command line should be:

    ffmpeg -loop 1 -i R0010183.jpg -i Location1B.wav -map 1:a -map 0:v -c:a copy -channel_layout 4.0 -c:v libx264 -vf scale=iw:ih*1.125 -pix_fmt yuv420p -b:v 40000k -bufsize 40000k -shortest Location1.mov

Could you share where you got your ffmpeg command line from, if you got it from somewhere online? We'd like to make sure the source is fixed too. :)

Thanks,
Dillon

**Comment by DrWig** [comment]
Think Mark got it from http://www.brucewiggins.co.uk/?p=666

I'll happily update my page..... Funny thing is, it's always worked for me
(with or without quad or 4.0 flags).

Cheers

Bruce

**Comment by dcower** [comment]
Ahhh, thanks Bruce! :) That would be great.

`quad` channel layout should not work on YouTube if it's specified, though it may have at one point; it will work in Jump Inspector though. YouTube only allows (i.e., succeeds in processing) ambisonic audio with unspecified or `4.0` channel layout.

**Comment by DrWig** [comment]
Thanks for the clarification.... I'll update my page 😊

Cheers

Bruce

**Comment by DrWig** [comment]
I have updated my page so as not to spread mis-information ;-)

cheers

Bruce

**Comment by M2Dr2** [comment]
Thanks for the information Dillion. I'll get to work and update you.

Yes, i forgot to mention my colleague and source of information was Bruce!!

**Comment by M2Dr2** [comment]
Hi Dillion. That worked a treat. Thank you very much for the rapid response.

**Comment by dcower** [comment]
Awesome, glad to hear it! And thanks as always, Bruce!
