### ISSUE TITLE
Custom Mesh and UV map

### ISSUE THREAD

**Issue by Fragilem17** [google/spatial-media#141]
I'm suggesting a way for some usage scenarios to safe on texture space for the locations where people are less likely to be looking.

I've described it here: https://docs.google.com/presentation/d/1bpMV6jnWfForXV1ZrsakY272TCbod9H8JBkiAzmtO-g/edit?usp=sharing

Would the custom mesh allow to do this?
[This is a comment on the Spherical Video V2 RFC (draft)]

**Comment by zougloub** [comment]
According on the Spherical Video V2 RFC, I think so; when will Youtube support it though?

**Comment by zougloub** [comment]
Hi @jamiesonpepper issue is closed after 8 years, I lost track... maybe add a closing statement? Thanks!

**Comment by jamiesonpepper** [comment]
Sorry, I was doing some clean-up of issues that had not been updated in years trying to focus mostly on keeping the tools compatible with current releases of Python.
