### ISSUE TITLE
Tool does not Work -Tcl wasn't installed properly-

### ISSUE THREAD

**Issue by psyferJP** [google/spatial-media#142]
Hi,　please help.

I try set 360-3D Video.
But "360.Video.Metatool.win" does not work.

Dubble Click .EXE file and the command screen disappears immediately.

Any other Software or Runtime environment Required ?
(I've never used ”Python” and any program code cause I'm not a programer)
Windows7 64bit

Command Screen capture (took it before it disappeared)
http://fast-uploader.com/file/7034817650765/

thank you.

**Comment by SahilMadan** [comment]
Hey psyferJP! Having a look at the error, it seems it might be related to this error with pyinstaller:
https://github.com/pyinstaller/pyinstaller/issues/1957

Could you try "Building standalone GUI application" instructions again, but install PyInstaller 3.1 instead of 3.2: https://github.com/google/spatial-media/tree/master/spatialmedia#building-standalone-gui-application

**Comment by darkeccho** [comment]
I have the same issue, installing 3.1 doesn't seem to solve the issue nor installing the latest version of v3 :( using windows 7 64bit. Using CMD i can clearly see the gui is not being built, any thoughts?

**Comment by Mabu2** [comment]
This problem still is happening.. it says..

LOADER: running gui.py

Can't find a usable init.tcl in the following directories....

This means that Tcl wasn't installed properly - failed to execute script gui

**Comment by shakena** [comment]
maybe very stupid newby respond.... if it would not make a new directory name in the temp directory, you could hardcode just one path in the windows system environments... and theoreticaly it will always be able to function..... i am on european machine, both win7 64x.... my laptop it works, my workstation it doesnt.... could someone maybe help me with seting up the script in a way it takes a hardcoded path over a new path each time it is loaded.... really would love to have it running smooth on both machines..... hope this comment has been of any help at all.... thank you developers... great creation you share..... ;-)

**Comment by nikita-nikiforov** [comment]
Have the same problem. Are there any solutions?
