### ISSUE TITLE
Request: support for batch processing/injecting

### ISSUE THREAD

**Issue by aggiejesus** [google/spatial-media#157]
Hello, I've used this tool without issue to get some 360 videos working properly in YouTube and other video players. However, I have hundreds of 360 videos that I need to inject spatial media metadata into, and I really wish I didn't have to run them through this tool _one-by-one_. If there is already some easy way to batch-inject the appropriate metadata into lots of videos, I would love to hear about it. If not, I would greatly appreciate the option being added to this tool, or made available in some derivative of it. Thank you.

**Comment by dcower** [comment]
Hi @aggiejesus,

You can use the metadata injector via the command line as described here: https://github.com/google/spatial-media/tree/master/spatialmedia

With a bit of scripting, it should be doable to batch process videos using it.

Hope this helps!
Dillon

**Comment by paulgailey** [comment]
Hi @aggiejesus I'd like to make a desktop solution to this. Would be great to get some further feedback from you before. Pls get in touch with me. Tx

**Comment by aggiejesus** [comment]
Hi @paulgailey , thanks for your interest. What can I do to help you with this?

**Comment by paulgailey** [comment]
hi @aggiejesus my email or other methods to contact me are available via my bio. I'd like to get more feedback beyond batch needs, gauge demand and know what typical filesize for batch are needed/if injection also includes audio etc.

**Comment by PHEDON** [comment]
hi i would like to know if you find any solutions.

**Comment by zackcase20** [comment]
Whoever created this program, thanks love you. But what in the world possessed you to only accept 1 input at a time?
