### ISSUE TITLE
Default video filename extensions missing valid but capitalized extension names for supported formats

### ISSUE THREAD

**Issue by ncouture** [google/spatial-media#158]
This ticket is specific to gui.py which defines *.mp4 and *.mov as the only valid extensions that can be opened using the gui.

On GNU/Linux this causes capitalized filenames with capitalized extension names to be missed, and since the "filetype" drop-down menu does not contain a generic "all file types" item, these files cannot be opened using the gui.

By making the file matching case-insensitive, this will no longer be an issue for GUI users.

**Comment by zacck** [comment]
Hello I'm happy to try take these on if I'm not stepping on any toes :)
