### ISSUE TITLE
What about MPEG DASH contents ?

### ISSUE THREAD

**Issue by LucasGregoryS** [google/spatial-media#160]
Hi ! 
I'm currently trying to implement the same kind of Spherical Metadata Injector, but in a MPEG-DASH scope.

I don't know if you're familiar with it, but I hope you'll be able to help me : 
Do I have to inject the RFC 1 & 2 boxes in all the MP4 files I'm generating (one per segment, contening MOOF & TRAF boxes instead of MOOV & TRAK ones), or should I only inject it in the Initial MP4 ?

I hope I'm being understandable, thank you in advance for your help !

**Comment by acolwell** [comment]
The spherical metadata is stored inside the MOOV so you should only need to place it in files that contain the MOOV box.
