### ISSUE TITLE
TCL failed to load Spatial Media Metadata Injector

### ISSUE THREAD

**Issue by GoofyOldGuyPlays** [google/spatial-media#165]
When I double click the Spatial Media Metadata Injector program, I get a very quick DOS windows that pops up and nothing else.  I recorded a video of it, just so I could read what it said.  As it flicked by, I managed to read the above error before it closed the window.  I see lots of people using this tool, and I've actually used it about a year ago on an older machine.  Why do I not even get a program when I double click?  (yes, extracted to a separate location and ran it from there, not within the actual zip file)

**Comment by nikita-nikiforov** [comment]
I have the same problem. Windows 7, 64 bit

**Comment by Jammer17** [comment]
I also have the same problem. Also on Win7, 64 bit.  How else can I inset 360 metadata onto a video?

**Comment by hellfi** [comment]
how to fix this:

1. open a cmd.exe window, execute _Spatial Media Metadata Injector.exe_, look at the paths it looks for, i.e.
2. _tkinter.TclError: _Can't find a usable init.tcl in the following directories:_
  [...] _F:/tcl8.5.15/library_ F:/tcl8.5.15/library
4. download **tcl8515-src.zip** and **tk8515-src.zip** from https://sourceforge.net/projects/tcl/files/Tcl/8.5.15/
5. extract **tcl8515-src.zip** to one of the directories from the error above, i.e. F:/tcl8.5.15/
6. extract **tk8515-src.zip**,rename the library folder to tk8.5 and move it to _F:/tcl8.5.15/library/_
7. run _Spatial Media Metadata Injector.exe_ again, it should work now.

I guess those libraries didn't make it to compilation somehow..

**Comment by GoofyOldGuyPlays** [comment]
Tried all of that.  Nope.  Didn't work.  I wish it would have.  Once those manual changes are added to the actual download and has been tested, I will certainly download the new version and try again.

**Comment by cswiatek** [comment]
hellfi's fix worked perfectly for me, although I placed the tcl8.5.15 folder in C:/Users. Make sure to follow the instructions carefully though. Remember - all you are doing with the tk8515 folder is removing the library folder, renaming it to tk8.5, and placing it within your tcl8.5.15/library folder.
