### ISSUE TITLE
Does not support AVI files

### ISSUE THREAD

**Issue by RoyWiggins** [google/spatial-media#170]
It does not appear to support .avi files- at least, the file picker doesn't let me select one. Does AVI not support the requisite metadata, or is this an artificial limitation? The most straightforward way I know to build a timelapse is with VirtualDub, which only(?) groks AVIs, so this issue is going to force me to find another workflow for building these. I know AVI is pretty crusty as container formats go, but...

**Comment by acolwell** [comment]
There is no plan to support AVI. We suggest you use FFmpeg or a similar tool to transform your AVIs into an MP4 file so it can be processed by the injector.
