### ISSUE TITLE
Gear 360 2017 Stitched cannot be injected (error)

### ISSUE THREAD

**Issue by Pablos3331** [google/spatial-media#171]
Guys, help.

 I`v tried with several video files from my Gear 360 2017, stitched with Gear 360 PC app.
I receive error as follows:
<img width="960" alt="2017-06-06" src="https://user-images.githubusercontent.com/29239159/26901426-22cc5466-4bd6-11e7-9e37-70b23f378528.png">

Can anyone tell me what might be the reason? Is it something that Gear 360 PC app does to the Video structure that unable Spatial to open it ?

Regards,
Pawel

**Comment by acolwell** [comment]
seems to be the same problem as #172
