### ISSUE TITLE
V2 stereo_mode enum values differ in mp4 and WebM

### ISSUE THREAD

**Issue by nalexeyev** [google/spatial-media#179]
**mp4 (st3d):** 0 - mono, 1- left-right, 2 - top-bottom, 3 - custom
**WebM:** 0 - mono, 1- left-right, 3 - top-bottom, 15 (provisional) - stereo-custom

**Comment by acolwell** [comment]
That is intentional. WebM already had an element for conveying stereo mode so it was reused. MP4 did not so a new st3d box was created. We didn't want to have to support all the modes specified in WebM or make MP4 definitions dependent on that container format spec so the enum values are different.
