### ISSUE TITLE
audio channel XYZ orientation relative to equirectangular video

### ISSUE THREAD

**Issue by claudeha** [google/spatial-media#183]
Here is an image showing an equirectangular video frame with various orientation points labelled:

![spatial-audio-in-360-video-orientation-question](https://user-images.githubusercontent.com/10728495/33577802-1dbe9170-d93c-11e7-9f0b-b71cc4a82cc1.png)

How should I prepare my spatial audio?  Which of AaBbCc correspond to ambisonic XYZ directions? (W is omnidirectional so no issue there).

I could not find guidance on this despite several hours of searching the internet, for documentation purposes a simple image as above but with +/-XYZ marked appropriately would be wonderful.

**Comment by mgorzel** [comment]
Hi @claudeha,

Assuming you want to use AmbiX convention, your Ambisonic audio channels will be:
Ch1: W (omni), Ch2: Y (left), Ch3: Z (up), Ch4: X (front). So, using your AaBbCc convention above, I believe that would correspond to +X-X-Y+Y+Z-Z.

Marcin
