### ISSUE TITLE
Video Error on YT after injecting Metadata

### ISSUE THREAD

**Issue by ElijahAjayi** [google/spatial-media#184]
Good afternoon all, hope all is well. I am having an issue with the video i've uploaded on YT. I follwed the instructions from YouTube as it states on their page. Once video plays on you tube, I can toggle the view, but end up with some shaded out areas in the video. Any insights?

Also, any way to remove/turn off audio from YT clip?

YT instructions followed: https://support.google.com/youtube/answer/6178631
YT video link: https://www.youtube.com/watch?v=Dj7dY6lmDms&feature=youtu.be

I'm on a Dell Latitude E6430 ATG using Windows 7 

![360 video clip](https://user-images.githubusercontent.com/34457967/33851995-ce472418-de86-11e7-937c-e942d3d6f257.PNG)

Any help would be greatly appreciated.

**Comment by suderman-google** [comment]
It appears that the video is not correctly projected to an [equirectangular projection](https://en.wikipedia.org/wiki/Equirectangular_projection).

Depending what camera you are using you will need to use the manufacturer's software to reproject the video. I am not certain what camera you are using but some common ones are the [ricoh theta](https://theta360.com/en/support/download/), [Kodak PixPro](https://kodakpixpro.com/Americas/support/downloads/),  or [Gear360](https://www.samsung.com/us/support/answer/ANS00060534/).

**Comment by ElijahAjayi** [comment]
I am using Gear 360.



Sent from my Sprint Samsung Galaxy S8.


-------- Original message --------

**Comment by kimomoki** [comment]
i have the gap too.

2017-12-12 9:33 GMT+08:00 ElijahAjayi <notifications@github.com>:

**Comment by ElijahAjayi** [comment]
The solution Suderman offered fixed my problem, thank you!
