### ISSUE TITLE
How to use personal HRTF data in omnitone?

### ISSUE THREAD

**Issue by bossesand** [google/spatial-media#187]
As availability of personal HRTF sets are now within reach for end users ( i have a set from IDA) I have a question.

Can a procedure be described on how to turn the HRTF into a format that can be used to replace the KU100 impulse responses in the javascript source?

I have extracted my personal IR for the elevations of +-35 degrees and directions +-135 and +-45,
should they be filtered and if so how to do that ? 

How should I the replacement in the javascript be done?

**Comment by mgorzel** [comment]
Hi @bossesand,

Unfortunately, custom HRTFs are not currently supported. However, if you are willing to spend some time, you could modify and use [this](https://github.com/resonance-audio/resonance-audio/blob/master/matlab/hrtf_data/sadie/sadieshhrirs.m) Matlab script to create your own set of spherical harmonic encoded HRTFs. Then, you should be able to swap the Omnitone filters [here](https://github.com/GoogleChrome/omnitone/tree/master/src/resources) and just follow the readme.

Hope that helps!
