### ISSUE TITLE
Please publish VR180 tools

### ISSUE THREAD

**Issue by ligoofing** [google/spatial-media#198]
Please publish a VR180 tools.
We can use it create VR180 format video  like spatialmedia tools.

**Comment by Vargol** [comment]
See my fork, https://github.com/Vargol/spatial-media if you can use equi-rectangular format.
I've also got mesh format working in by local copy but that is very camera specific as the mesh
as to match the camera distortion.

**Comment by brianpeiris** [comment]
In case anyone else didn't realize, Google has a tool specific to VR180 here: https://vr.google.com/vr180/apps/
