### ISSUE TITLE
Spatial Media Metadata Injector 2.1- won't load on OSX 10.11.6 (15G22010)

### ISSUE THREAD

**Issue by donstarnes** [google/spatial-media#204]
When I open the package and try the Unix executable, i get this error:

```
/Users/donstarnes/Downloads/Spatial\ Media\ Metadata\ Injector.app/Contents/MacOS/Spatial\ Media\ Metadata\ Injector ; exit;
Error loading Python lib '/var/folders/31/q3g8pqzn4l131jggwxn0bk900000gn/T/_MEITTUact/Python': dlopen(/var/folders/31/q3g8pqzn4l131jggwxn0bk900000gn/T/_MEITTUact/Python, 10): Symbol not found: _rootless_restricted_environment
  Referenced from: /var/folders/31/q3g8pqzn4l131jggwxn0bk900000gn/T/_MEITTUact/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/31/q3g8pqzn4l131jggwxn0bk900000gn/T/_MEITTUact/Python
logout
```

**Comment by mgorzel** [comment]
Hi @donstarnes, 

The standalone actually requires macOS 10.13. Apologies, there was an error in the release notes which I've now corrected. On an older version, you can still use the python script to inject the metadata or follow the instructions [here](https://github.com/google/spatial-media/tree/master/spatialmedia#building-standalone-gui-application) to build your own standalone app. Sorry for the trouble!
