### ISSUE TITLE
Meta Data injected fine, Youtube detects it fine but after a few days, nolonger works

### ISSUE THREAD

**Issue by mickyjj** [google/spatial-media#205]
Hello, 

This is likely a YouTube issue but as I can't be sure something else went wrong, I wanted to post here.
I first edited the video with Kodak PIXPRO_SP360_4K tool. (Input fisheye, output was equirectangular) I edited it with the free VSDC to add a title and music, and then saved as MP4. I injected meta data and uploaded (after testing with VLC). All seemed ok. I got 22 view, a thumbs up and the 360 view worked well ... now it appears just as a normal video but stretched as equirectangular projection without the ability to move perspective and no ability for VR headset. Whatever broke, I can't "unbreak" (at least for the moment). 

All my other videos with same workflow, same browsers, still work. Very odd. https://youtu.be/BNLMCXjSqx0

**Comment by Boscop** [comment]
I'm also interested to know the solution to this issue when you find out..

**Comment by mgorzel** [comment]
Hi @mickyjj, do you still experience any issues with the video? I've checked it today on both desktop and mobile and worked fine for me? Or is there any particular device / browser where you experience the problem? Cheers.
