### ISSUE TITLE
Added metadata but no spherical video is played at YT

### ISSUE THREAD

**Issue by daniel-dou** [google/spatial-media#21]
Sorry if this isn't the place to write about this, please point me there.

I've just used the script to add the metadata to a spherical video, getting this output:

    Loaded file settings
        Track 0
            Found: Spherical = true
            Found: Stitched = true
            Found: StitchingSoftware = Spherical Metadata Tool
            Found: ProjectionType = equirectangular
        Track 1

But the video uploaded on YT shows no 360 controls, like a normal one, although the 'processed' it's a little heavier than the original.

What could be wrong?

**Comment by AndrewHazelden** [comment]
Hi daniel-dou. Are you using Google Chrome to view the video on Youtube? Firefox doesn't seem to support the Youtube 360 video controls at the moment.

**Comment by daniel-dou** [comment]
Yes!

This is the video on YT: https://www.youtube.com/watch?v=SI177QUnjSU

I can see other 360 videos on YT rightly like this: https://www.youtube.com/watch?v=LByJ9Q6Lddo

**Comment by hbengali** [comment]
Could you recheck that you are uploading the output file and not the input file? I have made that mistake before.

**Comment by daniel-dou** [comment]
Yes, I've thought that too, and I'm sure, the output file was the one I uploaded

**Comment by suderman-google** [comment]
This may sound strange but the video link you send me for the video plays back as 360. Try viewing the video in incognito mode, it is possible a chrome extension changes the user agent to Firefox.

**Comment by daniel-dou** [comment]
suderman-google ... You're RIGHT!! I've just restarted and now I can see it!! Thanks!!

**Comment by suderman-google** [comment]
Happy to help :+1:.

**Comment by henrynho** [comment]
sorry I have a question I have a problem, I lower the 360 Video Metadata Tool.app of goolgle , but after using it in two videos, no longer works for me porq I get opened file,

any help please thanks
