### ISSUE TITLE
problem when try to inject the file video 

### ISSUE THREAD

**Issue by gianpi1718** [google/spatial-media#214]
hi , have a problem when try to inject file video after stitch from
 gear 360 , the problem is in photo 
![52647467_328891834415485_6463441853629857792_n](https://user-images.githubusercontent.com/47824319/53104035-f2377800-352e-11e9-8411-dadf9ad50c55.jpg)

**Comment by hk56740** [comment]
I get this problem as well!!!!Hope some knows the clue to solving it
