### ISSUE TITLE
YouTube Spatial Audio Issues

### ISSUE THREAD

**Issue by DrWig** [google/spatial-media#216]
Apologies if this isn't the right place for this, but I'm having issues getting YouTube to process spatial audio correctly.

Firstly, here's a version of the video that worked fine before XMas (using Premiere as the author and spatial media tag injector).  This works fine on desktop and mobile apps (60fps, 4096 x 2048 1st order ambiX)
https://youtu.be/yJ5WHHEhYOg

However, last week I tweaked the video and re-uploaded (using both Premiere [mp4+AAC] as mux'er/injector and FFMPEG and the spatial media tools as the mux'er and injector [mov + wav]) and YouTube is doing odd things.

First, all went well.  It processed correctly and the desktop YouTube correctly rotated the sound field when I panned the scene.   However, on mobile platforms (occulus Go and android youtube) the audio, although spatial, did not react to head/phone movement.

As of yesterday, the mobile platforms show the same issue, but now the desktop youtube will not play the videos at all......

Premiere Non-working video : https://youtu.be/MQG8YYrJC5E
FFMPEG + Spatial Media Tools : https://youtu.be/hSG5D_rkalI

Anyone got any ideas.  Is there something wrong with YouTube?  I've had spatial audio not process correctly before (many times!), but never had it working on one platform and not another!

cheers

DrWig

**Comment by DrWig** [comment]
ok, sorry for taking up space.  Reducing the frame rate to 30fps seems to fix the issue.

60fps seemed to be support before XMas (in the working video above).  Here's a link to the 30fps version I've just uploaded which correctly works on the desktop and mobile....
https://www.youtube.com/watch?v=Glgr4jOi_hw

**Comment by DrWig** [comment]
Just another update.....it seems as though YouTube has reprocessed the videos........all working now.......very odd!   Anyone hear have a hand in fixing this?

**Comment by mgorzel** [comment]
Hey @DrWig! The problem with these videos was *not* spatial audio but a transient issue with 60fps (spherical) videos. So, yes, they should be fixed now! Really sorry for the trouble!

**Comment by DrWig** [comment]
That's no problem at all, and thanks for the explanation @mgorzel  :-)
