### ISSUE TITLE
No module named tkfiledialog

### ISSUE THREAD

**Issue by improviseadaptovercome** [google/spatial-media#218]
Running the spatialmedia/gui.py on python 2.7:
` python gui.py`
```
Traceback <most recent call last>:
    File "gui.py", line 26, in <module>
        import tkfiledialog
ImportError: No module names tkfiledialog
```
Tried on 2.7 and 3.7, no use, some say tk had gone under change at 3.x, no use either.

**Comment by skillmatic-co** [comment]
This did not work for me. I'm getting this error once I click _Inject Metadata_:

https://capture.dropbox.com/wXadhoagXkVlTCKN
