### ISSUE TITLE
Windows Version Not Open

### ISSUE THREAD

**Issue by renatogabrielbr** [google/spatial-media#219]
The application on windows 10 is not open, i did install python, the path, restart the machine, try to start as administrator. when i tried to use the cmd option i got an error

$ gui.py
Traceback (most recent call last):
  File "C:\Users\tidyt\Downloads\spatial-media-2.1\spatial-media-2.1\spatialmedia\gui.py", line 26, in <module>
    import tkFileDialog
ModuleNotFoundError: No module named 'tkFileDialog'

**Comment by mgorzel** [comment]
Hi @tidytrax, are you using Python 3.x by any chance? This tool requires Python 2.7: 
https://github.com/google/spatial-media/tree/master/spatialmedia#usage

Also, could you check if the released binary version works for you? 
https://github.com/google/spatial-media/releases/download/v2.1/360.Video.Metadata.Tool.win.zip


Thanks!

**Comment by tecnoamigo** [comment]
It doesn´t work on WIN 10 64 bit. I tried to run as admin and it still doesn´t run. Can you help me?
