### ISSUE TITLE
I get this error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by hk56740** [google/spatial-media#224]
After I choose the mp4 file, I get this error, does anyone know how to solve this?
![image](https://user-images.githubusercontent.com/46671028/60764995-d7246980-a0c5-11e9-9890-2827298a79f7.png)

**Comment by hush-hush** [comment]
Same error here. Any idea what is causing this ?

**Comment by mrwm** [comment]
I also get a similar error. This happens on all the builds from 2.0, 2.1, and the master branch releases. The error appears on both the python `gui.py` and also the windows build exe. 

![Screenshot from 2020-12-09 22-44-38](https://user-images.githubusercontent.com/8944799/101731253-3aab8700-3a70-11eb-9136-5306d6efb949.png)

**Comment by Fabrice-TIERCELIN** [comment]
I confirm this solve the problem.
