### ISSUE TITLE
Ffmpeg add Spatial Media Metadata

### ISSUE THREAD

**Issue by wangpeng-teche** [google/spatial-media#226]
Can I add Spatial Media Metadata data using FFMPEG? In MP4 encoding, I tried to use ffmpeg's av_stream_add_side_data to add AVSphericalMapping data. It is useful in av_dump_format, but it is not in MP4. Is there a source code or class library for Windows C++?

**Comment by wangpeng-teche** [comment]
No one is maintaining it? There are very few people using this project.

**Comment by nbirkbeck** [comment]
There should be support for writing, but you'll have to lessen the strictness (e.g., to at least -strict unofficial):
https://github.com/FFmpeg/FFmpeg/blob/94bac7b3f8dcd8af33d9f7e18b4e4e73c73f98dd/libavformat/movenc.c#L2178

**Comment by Boscop** [comment]
@nbirkbeck I have ffmpeg 4.3, can you please tell me what the right invocation is to inject the metadata with ffmpeg?
I tried with `-strict unofficial` like:
> ffmpeg -i vid.mp4 -metadata:s:v spherical-video='<rdf:SphericalVideo xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/">GSpherical:Sphericaltrue</GSpherical:Spherical>GSpherical:Stitchedtrue</GSpherical:Stitched>GSpherical:StitchingSoftwareSpherical Metadata Tool</GSpherical:StitchingSoftware>GSpherical:ProjectionTypeequirectangular</GSpherical:ProjectionType></rdf:SphericalVideo>' -c copy -strict unofficial vid_360.mp4

It prints
```
    Metadata:
      handler_name    : VideoHandler
      spherical-video : <rdf:SphericalVideo xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/">GSpherical:Sphericaltrue</GSpherical:Spherical>GSpherical:Stitchedtrue</GSpherical:Stitched>GSpherical:StitchingSoftw
```

But the resulting video doesn't play as 360° video in VLC.
If I inject using the google injector, it plays correctly and has this metadata:
```
    Metadata:
      handler_name    : VideoHandler
    Side data:
      spherical: equirectangular (0.000000/0.000000/0.000000)
```

**Comment by suhaib-k** [comment]
It worked using the following:

`ffmpeg -i output.mp4 -metadata Spherical=true -metadata major_brand=isom -metadata minor_version=512 -metadata compatible_brands=isomiso2mp41 -metadata Spherical=true -metadata Stitched=true -metadata ProjectionType=equirectangular -metadata encoder=Lavf58.29.100 -metadata:s:v spherical-video='<rdf:SphericalVideo xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:GSpherical="http://ns.google.com/videos/1.0/spherical/">GSpherical:Sphericaltrue</GSpherical:Spherical>GSpherical:Stitchedtrue</GSpherical:Stitched>GSpherical:StitchingSoftwareSpherical Metadata Tool</GSpherical:StitchingSoftware>GSpherical:ProjectionTypeequirectangular</GSpherical:ProjectionType></rdf:SphericalVideo>' -c copy vid360.mp4`

**Comment by adiwithadidas** [comment]
@Boscop I know this a bit old, but did you found any solution for this ?

I am trying to add Spatial Medi Metadata in video through ffmpeg, so that players can detect the video as 360. 

Can you please guide me to a solution.

Thanks

**Comment by kairi003** [comment]
@adiwithadidas 
Unfortunately, I don't know how to do this with ffmpeg, but you can do this with [MKVMerge](https://mkvtoolnix.download/) as shown in [#159 ](https://github.com/google/spatial-media/issues/159#issuecomment-360522988).
Encode to mkv with `-c copy` , add metadata, and then convert back to mp4 with `-c copy -strict unofficial`.
