### ISSUE TITLE
Bug in atom.set

### ISSUE THREAD

**Issue by cgwennap** [google/spatial-media#23]
Hello,

I was randomly browsing your codebase when I noticed that atom.set appears to not actually set the contents of an atom properly due to the lack of the "self." prefix. In order to fix this bug, I believe

```python
def set(self, new_contents):
        """Sets the atom contents. This can be used to change an atom's
        contents"""
        contents = new_contents
        content_size = len(contents)
```
should be replaced with 

```python
def set(self, new_contents):
        """Sets the atom contents. This can be used to change an atom's
        contents"""
        self.contents = new_contents
        self.content_size = len(contents)
```

Hope this helps!

**Comment by dcower** [comment]
Looks like this is fixed now. Thanks for reporting!
