### ISSUE TITLE
I can't find how to inject 180vr mono metadata

### ISSUE THREAD

**Issue by Yooofi123** [google/spatial-media#236]
I have a 180 video I downloaded from youtube, I want to watch it on VLC but it doesn't know it's VR180 so I am trying this tool to inject the metadata but I am not seeing an option for 180, only 360 (which works great if the video was 360). what should I do? 

here's the dialog I am seeing:
https://imgur.com/a/7RHsrHr

thanks

**Comment by MagnusThome** [comment]
I'm also looking for a solution for 180 video.

**Comment by AssortedFantasy** [comment]
VR180 is supported by https://github.com/Vargol/spatial-media which is a fork of this project.
