### ISSUE TITLE
Can you make "pip install spatial-media" available?

### ISSUE THREAD

**Issue by shibababa** [google/spatial-media#237]
I am using python 3.7.5.
It is easier to use "pip install".

and, i want to use "import spatial-media" in python code.
If possible, make it happen.

**Comment by sidneys** [comment]
Hi,

I also think that would be a great idea. 

In the meantime however, why not give this approach a shot:


```bash
pip2 install git+https://github.com/google/spatial-media.git
```

Kind regards, S
