### ISSUE TITLE
Please note that this requires Python 2.7

### ISSUE THREAD

**Issue by Velro** [google/spatial-media#24]
The script doesn't work on Python 3.4.3 and its not noted anywhere on the readme, source file, or [support page](https://support.google.com/youtube/answer/6178631?hl=en) which version of Python should be used. It might be nice to note this somewhere for people that aren't regular Python users.

**Comment by suderman-google** [comment]
Thanks for the point out. Fix has been integrated in 4c5f63af54c21cbbc384a43f63ecfc12283e96fb.
