### ISSUE TITLE
Injecting metadata for equi-angular-cubemap (EAC) videos?

### ISSUE THREAD

**Issue by Boscop** [google/spatial-media#240]
Youtube serves 360° videos in [equi-angular-cubemap (EAC)](https://blog.google/products/google-vr/bringing-pixels-front-and-center-vr-video/) format but does it also support **uploading** in EAC format? (instead of equirectangular)
FFmpeg supports EAC but it seems this metadata injector doesn't seem to support it (?)
(When uploading in equirectangular format, YT converts it to EAC and serves that. But I want to avoid the conversion and upload in EAC already.)
If youtube supports uploads in EAC format, which metadata does it expect for this in the video container?

**Comment by gldecurtins** [comment]
As far as I know the GoPro MAX also stores the footage in EAC format on the internal SD card, including ambiX audio channels on the second track.
Their GoPro Player then converts the EAC into equirectangular - and somehow only outputs stereo.

In my usecase I would not have to modify / cut the captured video and if this tool could directly insert the EAC metadata, then I could get rid of a lot of steps, time and space in post processing.

Is there a chance that YouTube would expose their required and supported metadata settings for EAC? Or is the VR-hype over?
