### ISSUE TITLE
Doesn't work on videos downloaded from Youtube

### ISSUE THREAD

**Issue by mdamien** [google/spatial-media#250]
I downloaded a video from youtube in this format:

![image](https://user-images.githubusercontent.com/1469823/97422051-903b3280-190d-11eb-8f8f-4dd293bc6304.png)

When I try to inject the metadata both option don't work (with the gui) when playing the video on VLC, I get almost a good result with `StereoMode = top-bottom` turned off and very bad result with `StereoMode = top-bottom` added

**Comment by jamiesonpepper** [comment]
Closing older issue reports
