### ISSUE TITLE
Video inject issue

### ISSUE THREAD

**Issue by KevGin** [google/spatial-media#252]
I made a video for 360 degree panorama, and injected it in the program. But after I upload on Youtube or Vimeo, there is always an edge like spine in the connection of the video.
The image I use is 6000x3000, and the video is 1920x1080.
![截屏2020-12-10 下午10 03 18](https://user-images.githubusercontent.com/75786266/101764738-83c50f00-3b34-11eb-89be-50a70eed3dd8.png)

**Comment by KevGin** [comment]
I tried to change the ratio of the image and video, but did not solve the problem

**Comment by jamiesonpepper** [comment]
Closing older issue reports
