### ISSUE TITLE
Spatial Media Injector for Mac Not Working, Immediately Crashes

### ISSUE THREAD

**Issue by sunny-day123** [google/spatial-media#256]
I am trying to open the Spatial Media Injector for Mac and it is not opening and immediately crashing. I have tried to open this on several devices and it crashed immediately every time. In the past, I have had no issue opening this. Does anyone know any way I can open it?

**Comment by filmcafeSteve** [comment]
This fixed it for me: https://macdownload.informer.com/spatial-media-metadata-injector/download/#downloading

**Comment by newgen90** [comment]
> This fixed it for me: https://macdownload.informer.com/spatial-media-metadata-injector/download/#downloading

Oh damn! This is the answer. Thanks so much!

Tested and working on a Mac Mini M1 with MacOS Big Sur 11.2.2.

**Comment by gldecurtins** [comment]
Isn't this a little bit a shady source? What did they add to make it work?

**Comment by rahulchawla1803** [comment]
I have m1 pro macOS Monterey, it is not opening and immediately crashing. 
Is anyone working on it?
Is there a work around?

**Comment by FabriceLorenceau** [comment]
> > This fixed it for me: https://macdownload.informer.com/spatial-media-metadata-injector/download/#downloading
> 
> Oh damn! This is the answer. Thanks so much!
> 
> Tested and working on a Mac Mini M1 with MacOS Big Sur 11.2.2.

This did not work for me.

**Comment by williamyee281** [comment]
Not working on Macbook Pro M 2  running OS Ventura 13.0

Doesn't start as the OS cannot verify the developer.  It stops from opening and request to move it to the trash

Any suggestions?

**Comment by jamiesonpepper** [comment]
Instructions in this thread https://github.com/google/spatial-media/issues/261#issuecomment-1590148367 to build from source, new release is coming!

**Comment by livingperson** [comment]
> Instructions in this thread [#261 (comment)](https://github.com/google/spatial-media/issues/261#issuecomment-1590148367) to build from source, new release is coming!

Followed the 261 instructions. Got this when conducting the test:

> Traceback (most recent call last):
>   File "/spatial-media-2.1/spatialmedia/gui.py", line 26, in <module>
>     import tkFileDialog
> ModuleNotFoundError: No module named 'tkFileDialog'
> 

So it seems it no longer works. I'm running Sonoma on M1 Mac.

**Comment by jamiesonpepper** [comment]
@livingperson Are you able to use the command line method as noted in https://github.com/google/spatial-media/issues/256#issuecomment-1127232522?
