### ISSUE TITLE
2.1 not opening on BigSur 11.1

### ISSUE THREAD

**Issue by fishifilms** [google/spatial-media#260]
First time user, the application 'quit unexpectedly' straight away every time I open it. Any help is greatly appreciated

**Comment by gldecurtins** [comment]
Hi fishifilms

I suggest to use it in command line mode:

1. Open terminal
2. Take care that Python and git are installed
3. *git clone https://github.com/google/spatial-media.git*
4. *cd spatial-media*
5. *python spatialmedia <filenames...>* to inspect the files
6. *python spatialmedia -i <input> <output>* to inject the metadata

Documentation can be found here: [README.md](https://github.com/google/spatial-media/blob/master/spatialmedia/README.md)

**Comment by marcstreeter** [comment]
you may need to specify "python2" as using "python" on your system may be defaulted to python3 and this tool is currently written for python 2.7 (not 3 where it was giving me errors)
