### ISSUE TITLE
UI work for M1 Mac?

### ISSUE THREAD

**Issue by leon-do** [google/spatial-media#261]
I tried opening the UI version for the M1 Mac. It opens then immediately closes. 

Anyone with the same problem?

Anyone find a solution?

**Comment by marcstreeter** [comment]
you can use the command line as mentioned here https://github.com/google/spatial-media/issues/260

**Comment by pedrocadiz13** [comment]
Here's a nicer work around:

 1. Download master as zip and unpack. Release 2.1 requires python2, but the master has been updated for python3.
 
 2. Install python3 via homebrew (if you don't already have it) :
 	
 	brew install python 
 	brew link python

3. Install python-tk

   brew install python-tk
   
4. test with comand:

python3 /Users/peter/Projects/Python/spatial-media-master/spatialmedia/gui.py

(You'll need to change path to wherever you unpacked the zip).

You can add the above line to a script, it wourks, but annoyingly also opens a terminal window. To get round this, use pyinstaller to create an app instead:

5. install pyinstaller

pip3 install -U pyinstaller
python3.11 -m pip install --upgrade pip

6. Build the app

cd /Users/peter/Projects/Python/spatial-media-master/spatialmedia
pyinstaller gui.py --windowed

This will create the gui.app in cd /Users/peter/Projects/Python/spatial-media-master/spatialmedia/dist

7. Rename "gui.app" to "Spatial Media Metadata Injector.app"

8. Copy "Spatial Media Metadata Injector.app" to your Applications folder.

**Comment by livingperson** [comment]
> 4\. test with comand:
> 
> python3 /Users/peter/Projects/Python/spatial-media-master/spatialmedia/gui.py

Did this, and get:

Traceback (most recent call last):
  File "/spatial-media-2.1/spatialmedia/gui.py", line 26, in <module>
    import tkFileDialog
ModuleNotFoundError: No module named 'tkFileDialog'

**Comment by pedrocadiz13** [comment]
> > 4. test with comand:
> > python3 /Users/peter/Projects/Python/spatial-media-master/spatialmedia/gui.py
> 
> Did this, and get:
> 
> Traceback (most recent call last): File "/spatial-media-2.1/spatialmedia/gui.py", line 26, in import tkFileDialog ModuleNotFoundError: No module named 'tkFileDialog'

The workaround I provided above only works with python 2. You might be able to get it to work with python 3, but might need some refactoring. Unfortunately I'm not a python dev, so don't know how much work that would involve.
