### ISSUE TITLE
With large videos fails

### ISSUE THREAD

**Issue by carlosnewmusic** [google/spatial-media#268]
Show this failure
![imagen](https://user-images.githubusercontent.com/19379457/172071551-b5e0b8ab-a4bf-457d-88b2-241e4d05bb77.png)
with the video with this encoding
![imagen](https://user-images.githubusercontent.com/19379457/172071597-1a884082-2497-4f8c-8e93-7932f5b49df0.png)

**Comment by jamiesonpepper** [comment]
Try cloning the current master branch and testing via command line.
