### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by kkotaro0111** [google/spatial-media#27]
i try it.

```shell
$ ./360VideosMetadata.py -i input.mp4 output.mp4
```

show console.
```
File "./360VideosMetadata.py", line 145
  print "Error, invalid size in "+ name+ " at "+ position
```

- MacOSX 10.10.3
- python 3.3.6(default, Mar 6 2015, 23:47:41)

**Comment by kkotaro0111** [comment]
Sorry, I reading mistake.
I try this script with python 2.7.10, could be confirmed running.

**Comment by ascherkus** [comment]
Thanks for confirming what the issue was! Indeed we assume Python 2.x at this point in time.
