### ISSUE TITLE
Failed to load file

### ISSUE THREAD

**Issue by gamersalpha** [google/spatial-media#270]
Hello Evryone so i try to download the link here : 

https://github.com/google/spatial-media/releases

but when i lunch my video i got this message how to now what is wrong please 👍 

![image](https://user-images.githubusercontent.com/32466950/183031445-cc3c44ab-158e-4c1d-ab04-783621c616af.png)

**Comment by gamersalpha** [comment]
how to see log to see what's happening please

**Comment by gamersalpha** [comment]
again i got this error on all my video come from gear 360 

![image](https://user-images.githubusercontent.com/32466950/184396225-266f0a55-0d7f-49bb-a7a4-a11e60b53076.png)

i found

**Comment by gamersalpha** [comment]
Hello maybe the video got some meta

can u delete them and install the good one please

**Comment by jamiesonpepper** [comment]
Try cloning the current master branch and testing via command line.
