### ISSUE TITLE
After injecting spacial media on an 8k file, via cli (on m1) file doesnt work

### ISSUE THREAD

**Issue by zippytiff** [google/spatial-media#272]
Hi,

So the cli has been working great on some 6k files

I have now tried on some 8k files, but after injecting the spacial media the video does work (eg wont load in vlc)

Here is the command im using.... any ideas ? there is no error after running the command, the output looks normal

spatial-media % ../.pyenv/versions/2.7.18/bin/python spatialmedia -i ../Desktop/VID_20220820_203307_00_012_180_crf14_360_537373684_ahq12.mp4 ../Desktop/VID_20220820_203307_00_012_180_crf14_360_8K_360.mp4
Processing: /Users/tim/Desktop/VID_20220820_203307_00_012_180_crf14_360_537373684_ahq12.mp4
Saved file settings
	Track 0
		Spherical = true
		Stitched = true
		StitchingSoftware = Spherical Metadata Tool
		ProjectionType = equirectangular
	Track 1

**Comment by jamiesonpepper** [comment]
Can you confirm the camera you are testing on or provide a small sample file from it to test with?
