### ISSUE TITLE
error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by waitingforDBZBT3remake** [google/spatial-media#273]
On very few videos that I try to convert to 360 view, I get the error message from the title. I dont know what to do, please help me out  🎷🗿

**Comment by AnonymousEliforp** [comment]
Try downloading the latest code from the master branch, then launching the gui manually from spatialmedia/gui.py.

**Comment by reneilpascua** [comment]
i had this issue for a video which happened to be my largest (10+GB)
my fix for it was to clone the spatial-media repo, go into its root, and used the command
`python spatialmedia -i <input file path> <output file path>`
