### ISSUE TITLE
VLC and Samsung Gear 360 2017: Wrong injection

### ISSUE THREAD

**Issue by tkalfaoglu** [google/spatial-media#274]
The video is rendered wrongly after injection with spatial-media when a Samsung Gear 360 2017 file is given to the injector. The native version of this device is to create two 180-degree images/videos side by side.
See http://kalfaoglu.com/tmp/Screenshot_20230108_160214.png

**Comment by jamiesonpepper** [comment]
@tkalfaoglu In this case I believe you would need to find something to restitch or reformat before injecting. I do not own the device you noted, but on a Kodak PixPro VR 180 I had to export/unfold in Equirectangular format while specifying the correct orientation of the device. Any other option ended up with a distorted view.

Based on your screenshot it looks like it is exporting in Side by Side (SBS) which may work directly in a VR headset all on its own but not on on VLC, Windows Media Player, or YouTube 180/360/VR after injecting with the tool.

Hope this helps!

**Comment by jamiesonpepper** [comment]
Alternatively you may be able to leave your video as is and use the [--stereo switch with the left-right flag](https://github.com/google/spatial-media/tree/master/spatialmedia#--stereo) as that seems to be the way to process SBS input.

**Comment by tkalfaoglu** [comment]
Thank you -- I tried the stereo switch and it worked -- however black semi-circles are visible in the resulting video. . Please see my new issue on this topic..
