### ISSUE TITLE
Amer lb

### ISSUE THREAD

**Issue by Amerlbamer** [google/spatial-media#277]
كيف يمكنني زيدات مشاهد والاشتراك قي قناتي على يوتيوب

**Comment by jamiesonpepper** [comment]
عذرًا ، هذا ليس مكانًا يوفر معلومات حول كيفية زيادة مشتركي YouTube. يمكنك العثور على إجابات لهذه الأنواع من الأسئلة هنا: https://support.google.com/youtube/answer/11616410؟hl=ar
