### ISSUE TITLE
Gear 360 2017 model: left-right do not overlap or match

### ISSUE THREAD

**Issue by tkalfaoglu** [google/spatial-media#278]
When used with a Gear 360 2017 camera, spatialmedia with left-right option, the two halves of the video do not match. Camera set for 4k..  
Command line:
$ spatialmedia -i -s left-right 360_0090.MP4  aha.mp4

See image..
![Screenshot_20230206_153134](https://user-images.githubusercontent.com/837835/216972402-616df928-f15d-4e4e-a1bb-9623349564d2.png)

**Comment by ostinator** [comment]
Pretty sure you need to stitch together prior to using VLC. I've been using the Samsung Gear 360 ActionDirector [https://www.samsung.com/us/support/answer/ANS00066650/] (only available to download until 2024) which automatically stitches the video. However, the stitched video doesn't have the correct metadata for VLC to recognise so may have to use the VLC equirectangular injector somewhere on GitHub, or by other means.

**Comment by jamiesonpepper** [comment]
Any chance you can post the source video somewhere for someone to test with or analyze?

**Comment by gamersalpha** [comment]
got the same issue

**Comment by niluss** [comment]
You have to stitch it first
