### ISSUE TITLE
Ambisonic audio with non spherical standard 2D video

### ISSUE THREAD

**Issue by noahneumark** [google/spatial-media#288]
Are there plans to provide a way to use ambisonic audio on a normal non spherical video? This would open up a lot more content from producers as there are a lot more ambisonic tools becoming available, and YouTube could be an excellent distribution platform if not for the current limitation that it must be attached to a spherical video. With so many users that consume content using earbuds with headtracking capabilities (AirPods Pro, Beats Fit Pro etc.) there is already a massive potential audience if only Google would remove this limitation.

**Comment by jamiesonpepper** [comment]
Thanks for the suggestion Noah! 

I would advise raising this feedback with the YouTube folks via the 'Send Feedback' button so that they can get it directly.

Much appreciated,

Jamie
