### ISSUE TITLE
Release 32-bit Windows version of script

### ISSUE THREAD

**Issue by ascherkus** [google/spatial-media#31]
User feedback: released binary doesn't work on 32-bit windows and user claims cannot run script directly since it requires Python 2.x and they have Python 3.x

**Comment by gwendalmorvan** [comment]
Please, please, do so !
For now, with my 32-bit windows version, I'm kind of stuck...

**Comment by martinemartine** [comment]
me to, how can it work on windows 32, 7?

**Comment by dcower** [comment]
The latest release (v2.0) supports Windows 7 32-bit (x86).
