### ISSUE TITLE
[Question] is there any player do support the spatial format.

### ISSUE THREAD

**Issue by Ood-Tsen** [google/spatial-media#32]
I try the script '360VideosMetadata.py',
 it does add atom in the mpeg 4 files.

But is there any player support this format and render it on the screen ?

Thanks in advance.

**Comment by ascherkus** [comment]
Aside from uploading to YouTube I'm not aware of any native player support at this time.

**Comment by ascherkus** [comment]
(Thanks for asking, by the way!)
