### ISSUE TITLE
Injector not working on large video files?

### ISSUE THREAD

**Issue by daxon** [google/spatial-media#33]
I couldn't find anywhere else to post this issue. Youtube haven't help yet: https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!topic/youtube/jZJyJn4WTLg;context-place=forum/youtube

I have rendered a Apple Pro Res 422 HQ file which results in a 31 GB .mov

I rename it to .mp4 and inject the metadata. Save a new file and waited 10+ hours and the file never gets written. (tried with terminal for a night as well)

I tested to see if it was .mov issue or Injector handling huge files:

Tested the same render of a 1 second version Apple Pro Res 422 HQ file which results in a 330 MB .mov
I rename it to .mp4 and inject the metadata. Save a new file and it worked. (uploaded and played as a 360 video)

So the injector works on .mov renamed .mp4 on small files.

Large files? Please help

**Comment by dcower** [comment]
Hi @daxon, we believe this issue should be fixed now. Please reopen if you encounter this issue again. Thanks!
