### ISSUE TITLE
Full area smaller than cropped area in RFC xml spec example

### ISSUE THREAD

**Issue by bhautikj** [google/spatial-media#39]
In [appendix 1 of the rfc](https://github.com/google/spatial-media/blob/master/docs/spherical-video-rfc.md#appendix-1---global-metadata-sample), the full area appears to be smaller than the cropped area:

```xml
  <GSpherical:CroppedAreaImageWidthPixels>1920</GSpherical:CroppedAreaImageWidthPixels>
  <GSpherical:CroppedAreaImageHeightPixels>1080</GSpherical:CroppedAreaImageHeightPixels>
  <GSpherical:FullPanoWidthPixels>1900</GSpherical:FullPanoWidthPixels>
  <GSpherical:FullPanoHeightPixels>960</GSpherical:FullPanoHeightPixels>
  <GSpherical:CroppedAreaLeftPixels>15</GSpherical:CroppedAreaLeftPixels>
  <GSpherical:CroppedAreaTopPixels>60</GSpherical:CroppedAreaTopPixels>
```
I feel like I'm missing something here - is this an error, or is there something I'm not understanding about how the cropped/full areas work? Is the 'full' area a resize of the total 'cropped' area once the left and top pixel offsets have been added? I'd love to see a diagram that lays these areas out if possible :)

**Comment by jprouty** [comment]
Hi there,

The spec borrows a lot from the Photo Sphere Metadata spec. They have a nice diagram and more description of the indented usage.

https://developers.google.com/streetview/spherical-metadata

Cheers,
Jeff

**Comment by bhautikj** [comment]
@jprouty that's great - it clarifies a lot. Thanks!
