### ISSUE TITLE
Should check for .webm not just .mkv

### ISSUE THREAD

**Issue by ascherkus** [google/spatial-media#4]

**Comment by aimkeepachieve** [comment]
I usually use iDealshare VideoGo to convert video and audio files

It can convert WebM to almost all kinds of video formats like WebM to MP4, WebM to AVI, WebM to WMV, WebM to FLV, WebM to MOV, MKV, ASF, RM, DV, FLV, Apple Prores, etc.

It also enables to convert MP4 to WebM, AVI to WebM, WMV to WebM, MKV to WebM, FLV to WebM and more.

It also can extract audio from WebM files, for example, WebM to MP3, WebM to WAV, FLAC, AAC, AC3, WMA, AIFF, AU, MP2, OGG, Apple Lossless M4A, FLAC, WAV, DTS, etc;

It even can edit WebM file, for instance, trim, crop, increase volume, join several files, adjust bitrate, sample rate, change channel, take snapshot, and add subtitle/watermark to the source file, etc.

Step by step guide at http://www.idealshare.net/video-converter/webm-to-avi-converter.html
