### ISSUE TITLE
mercator stereo issues

### ISSUE THREAD

**Issue by przemyslawpluta** [google/spatial-media#42]
This is the layout of the original video - mercator stereo.

![img](http://s22.postimg.org/5byqjh1kh/Screen_Shot_2015_10_31_at_20_09_43.png)

Running default:
```bash
./360VideosMetadata.py -i ./original.mp4 out.mp4
```
outputs:
```
Saved file settings
	Track 0
		Found: Spherical = true
		Found: Stitched = true
		Found: StitchingSoftware = Spherical Metadata Tool
		Found: ProjectionType = equirectangular
	Track 1
	Track 2
```

produces incorrect 360 video, same goes for:

```bash
./360VideosMetadata.py -i --stereo='top-bottom' ./original.mp4 out.mp4
```
outputs:
```
Saved file settings
	Track 0
		Found: Spherical = true
		Found: Stitched = true
		Found: StitchingSoftware = Spherical Metadata Tool
		Found: ProjectionType = equirectangular
		Found: StereoMode = top-bottom
	Track 1
```
Both 360 vides are displayed incorrectly on yt. Am I missing something?

Thanks .

**Comment by hbengali** [comment]
Support for stereo 360 video playback has not yet launched on YouTube. An announcement will be made on the [YouTube blog] (http://youtube-global.blogspot.com/) as soon as this support goes live.

**Comment by przemyslawpluta** [comment]
@hbengali there is an entire [360 video section](https://www.youtube.com/channel/UCzuqhhs6NWbgTzMuM09WKDQ) on yt already?

**Comment by sphericvr** [comment]
Just spherical projection, not stereo 360.

**Comment by przemyslawpluta** [comment]
@sphericvr yes already tested crop with spherical projection and it works as expected. Are there any plans to support stereo 360?

**Comment by sphericvr** [comment]
Back in July YTCreators posted to Twitter that support was coming.

https://twitter.com/YTCreators/status/624370336595771394?ref_src=twsrc%5Etfw

**Comment by przemyslawpluta** [comment]
@sphericvr shall I assume that once yt stereo 360 is supported `StereoMode = top-bottom` will be an option to choose?

**Comment by sphericvr** [comment]
@przemyslawpluta I don't have any more information than you do. I'm waiting to see what Google's Jump program produces. Kolor (and therefore GoPro) supports either over/under or side by side.

**Comment by przemyslawpluta** [comment]
Here we go [YouTube now supports VR video](http://youtube-global.blogspot.co.uk/2015/11/youtube-presses-play-on-virtual-reality.html) :blush:

**Comment by przemyslawpluta** [comment]
@suderman-google @sphericvr I have a small issue with one of the 360 stereo VR sequences. Selection top-bottom works as expected but original file:

![img](http://s10.postimg.org/qtflc0ddl/Screen_Shot_2015_11_05_at_23_30_48.png)

contains 2 squares at the right side of left and right eye of the footage. Looks like they are used to cover top and bottom or the 360 video once reassembled. Video looks correctly in oculus not yt.

Any thoughts? Thanks.

**Comment by sphericvr** [comment]
I think you're right about their usage. Crop them out with your software of choice (Premiere Pro, After Effects) before applying metadata and uploading to youtube.

**Comment by przemyslawpluta** [comment]
@sphericvr testing ...

**Comment by przemyslawpluta** [comment]
@sphericvr did you use any software to add graphics into 360 stereo footage?

**Comment by sphericvr** [comment]
@przemyslawpluta I use Cinema 4D.

**Comment by przemyslawpluta** [comment]
Any additional plugins etc?

**Comment by sphericvr** [comment]
No. Just rendering out with a sphere using the reflection channel.

**Comment by przemyslawpluta** [comment]
@sphericvr did you use ae or fc?

**Comment by sphericvr** [comment]
After Effects.

**Comment by przemyslawpluta** [comment]
@sphericvr am I correct to assume AE for pure post and most of the graphical elements, text etc. in cinema?

**Comment by sphericvr** [comment]
Yes. Cineware allows you to use C4D assets natively in AE.

**Comment by przemyslawpluta** [comment]
@sphericvr looks better but bottom and top look wired ... merging into a single point.

![img](http://s1.postimg.org/g97ajupqn/Screen_Shot_2015_11_06_at_00_32_59.png)

**Comment by suderman-google** [comment]
So the example projection you are showing is not purely an equirectangular frame but rather a partial equirectangular frame with the top and bottom of the sphere stored on the side.

My suggestion is to reprojection the video from source into equirectangular as the details for how the top / bottom is stored on the right can vary significantly.
