### ISSUE TITLE
Investigate support for QuickTime .mov formats

### ISSUE THREAD

**Issue by ascherkus** [google/spatial-media#43]
Today you can get it to work by changing the file extension from .mov to .mp4 ... but ideally we should have more robust support (e.g., checking ftyp) and/or defining the exact amount of QuickTime-specific stuff we want to support.

**Comment by suderman-google** [comment]
FTYP worked still TBD.

**Comment by dcower** [comment]
.mov support is live in the latest version of the Spatial Media Metadata Injector.
