### ISSUE TITLE
File write progress would be nice

### ISSUE THREAD

**Issue by ascherkus** [google/spatial-media#44]
When using the script on large inputs (e.g., >10GB) it'd be nice to have progress indicator of some sort because it just sorta hangs there.

Not high priority or anything (hey, cp doesn't print out progress!) but something to consider (that or magically make the IO performance super fast -- but I haven't benchmarked this yet and iotop seems to claim it was using a good chunk of available IO bandwidth)

**Comment by jamiesonpepper** [comment]
Closing older issues
