### ISSUE TITLE
MKV/WebM path totally broken

### ISSUE THREAD

**Issue by ascherkus** [google/spatial-media#45]
Looks like this code path is still accessible and it's buggy.

First bug: it always prints out a file overwrite prompt if even if file doesn't exist.
```
$ python 360VideosMetadata.py -i -s top-bottom foo.webm bar.webm
Processing:  /path/to/foo.webm 

Press y <enter> to confirm overwrite
Saved file settings
```

Second bug: it doesn't actually inject anything!
```
$ python 360VideosMetadata.py bar.webm
Processing:  /path/to/bar.webm

Loaded file settings
```

**Comment by suderman-google** [comment]
I'll rip everything else related to mkv out and mkv support can be added TBD.

**Comment by suderman-google** [comment]
So this is the old script prior to the refactor + gui which technically does still work (though it is unable to detect when it fails). I'll still remove support.

**Comment by ascherkus** [comment]
what's our plan for the old script? can we move away from maintaining two versions?

**Comment by suderman-google** [comment]
I was planning to remove it after launch. The main reason we maintained the original was to make sure that previous links remained valid. As all of the upload docs will be updated removing it should no longer cause issues.

**Comment by suderman-google** [comment]
Added a pull request for removing old 360VideosMetadata.py tool.
