### ISSUE TITLE
360 intervals in a video

### ISSUE THREAD

**Issue by robbiefrankle** [google/spatial-media#47]
I apologize if this isn't the right place to ask this type of question, but if someone can point me in the right direction it would be greatly appreciate it. 

I'm wondering if there is a way to make portions of a video 360 degrees. Basically I would like some portions of a video to be standard 2D and other parts to be 360 in the same video. Is there a way to specify in the metadata that from 0 to 30 seconds show 2D video and from 30 seconds to 60 seconds put the video in 360 mode. Or possibly by frames instead of seconds?

**Comment by jprouty** [comment]
That is not supported at this time. All or nothing for now.

**Comment by robbiefrankle** [comment]
Thanks for the quick response! Are there any plans in the near future to add this option?

**Comment by jprouty** [comment]
You're the first one to mention it. No plans yet.

**Comment by robbiefrankle** [comment]
Okay. Thanks!
