### ISSUE TITLE
Prebuilt tool does not run on Windows 10

### ISSUE THREAD

**Issue by suderman-google** [google/spatial-media#50]
Current iteration of the tool does not appear to run on Windows 10.

**Comment by ddfire** [comment]
is there any workaround? (without change the OS)
Thanks

**Comment by suderman-google** [comment]
We are working on a new build that will work on Windows 10. I will update when the build is updated.

Another option is to run the gui.py from commandline if you are familiar with python / commandline.

**Comment by ddfire** [comment]
thanks!!!!

2016-02-01 14:33 GMT-03:00 suderman-google <notifications@github.com>:

> We are working on a new build that will work on Windows 10. I will update
> when the build is updated.
>
> Another option is to run the gui.py from commandline if you are familiar
> with python / commandline.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/spatial-media/issues/50#issuecomment-178087330>
> .
>



-- 
 (\__/)
(='.'=)This is Bunny. Copy and paste bunny into your
(")_(")signature to help him gain world domination.

**Comment by dcower** [comment]
The latest version of the Spatial Media Metadata Injector is confirmed to work on Windows 10. Please reopen if you have any further issues running on Windows 10 though.
