### ISSUE TITLE
Ambisonics support live in player?

### ISSUE THREAD

**Issue by evanmang** [google/spatial-media#56]
I tried exporting a test file with a first order ambisonics mix and injecting the metadata with the current injector, but my upload to youtube doesn't seem to play the ambisonic mix correctly. Is support live on the player, or is this just in preparation for a future rollout?

**Comment by dcower** [comment]
Thank you for the interest! The spatial audio metadata is not currently supported.

**Comment by evanmang** [comment]
Cool. thanks! Looking forward when it is!

**Comment by dcower** [comment]
Spatial audio is now supported in YouTube. See [Use spatial audio in 360-degree and VR videos](https://support.google.com/youtube/answer/6395969?hl=en) from YouTube Help and [Spatial Audio](https://support.google.com/jump/answer/6399746?hl=en&ref_topic=6399824) from Jump Help.
