### ISSUE TITLE
Encoder for tool

### ISSUE THREAD

**Issue by danrossi** [google/spatial-media#59]
Hi I would like to investigate this spec and hopefully integrate into dash.js and three.js projects. How do you go about encoding a video with an ambisonics wav stem ? 

Ffmpeg doesn't seem to support such things. Is there example mp4 files to test this tool ? A bit unsure how to package a file first for testing the tool and spec. 

I guess packagers will need to support the final output also. 

Are these individual streams muxed in or do the players need to parse and decode and handle panning with audio apis ? I've yet to find how it would be possible decoding the 4 channel ambisonics stream yet.

**Comment by dcower** [comment]
Hey @danrossi, sorry about the delay here. For prototyping, I suggest using [FFmpeg](https://ffmpeg.org) to mux video with ambisonic audio. Could you explain the issues you were having with FFmpeg?

The metadata injector supports MP4 and MOV containers. You can use 4-channel AAC with both, and you can use 4-channel uncompressed audio with MOV. I suspect browser support for the latter is lacking though.

All ambisonic decoding/rendering needs to be done on the player side.

**Comment by dcower** [comment]
I'm closing this issue for the time being. Please see [Spatial Audio](https://support.google.com/jump/answer/6399746?hl=en&ref_topic=6399824] in the Jump Help documentation for some more information.
