### ISSUE TITLE
windows 32

### ISSUE THREAD

**Issue by martinemartine** [google/spatial-media#61]
Hello, 

Where can I find the exe for windows 32 ? Or how can the present download for windows work on windows 32 ? It doesnt execute at all. 

Kindly regards, Martine

**Comment by dcower** [comment]
Hi @martinemartine,

The latest version of the Spatial Media Metadata Injector should work on 32-bit Windows. Please let us know if you're still running into issues though.

Thanks,
Dillon

**Comment by martinemartine** [comment]
Ok, thanks. 

Date: Wed, 20 Apr 2016 15:26:31 -0700
