### ISSUE TITLE
Injection not seeing input and output files

### ISSUE THREAD

**Issue by patricktr** [google/spatial-media#62]
I'm trying to inject InitialView metadtata into a file. I have used the standalone GUI app to inject spherical tag, and that works. But when I type
`python spatialmedia -i [--InitialViewRollDegrees=80] v1.mp4 v1_80.mp4`
the command line returns "Injecting Metadata requiores both an input and output file.

I have tried this several ways, but it does not seem to "see" the two files I have given it. What's going on here?
![screen shot 2016-02-18 at 3 57 06 pm](https://cloud.githubusercontent.com/assets/6923047/13157903/52069cae-d658-11e5-9a31-37d9dba7705f.png)

**Comment by suderman-google** [comment]
You are missing the -- infront of InitialViewRollDegrees=80, however --InitialViewRollDegrees=80 is optional.

Just try:
python spatialmedia -i v1.mp4 v180.mp4

**Comment by patricktr** [comment]
Hmm, I've tried it with the -- in a variety of places with no success.
`Patricks-iMac:spatial-media patrick$ python spatialmedia -i v1.mp4 v2.mp4
Processing: /Users/patrick/Documents/Github/spatial-media/v1.mp4
Saved file settings
	Track 0
		Spherical = true
		Stitched = true
		StitchingSoftware = Spherical Metadata Tool
		ProjectionType = equirectangular
	Track 1
Patricks-iMac:spatial-media patrick$ python spatialmedia -i [--InitialViewRollDegrees=80] v1.mp4 v1_80.mp4
Injecting metadata requires both an input file and output file.
Patricks-iMac:spatial-media patrick$ python spatialmedia -i --[InitialViewRollDegrees=80] v1.mp4 v1_80.mp4
usage: spatialmedia [options] [files...]

By default prints out spatial media metadata from specified files.
spatialmedia: error: unrecognized arguments: --[InitialViewRollDegrees=80]
`

I know that the initial view is optional, but it is also the sole thing I am trying to accomplish -- right now I have a file that was shot on an angle against the horizon, and am trying to fix it. Of course, now that I know that YouTube does not yet support InitialView, this may be a moot point. Still, I'd love to figure out how to do this.

**Comment by suderman-google** [comment]
Square brackets indicate optional parameters and should not be included, the command you need to run is as follows:

python spatialmedia -i --InitialViewRollDegrees=80 v1.mp4 v1_80.mp4

**Comment by sphericvr** [comment]
Why not fix it in AE or Premiere? Want to share the file and I can help you out?

**Comment by dcower** [comment]
Hey @patricktr, sorry for any confusion here. The injector doesn't have support for InitialViewRollDegrees currently, so that's why you're unable to use the option. As @sphericvr mentioned, the right way to correct this today is by using video editing software.

**Comment by patricktr** [comment]
Okay thanks all. We can fix it in AE or premiere, but are interested in learning the code end of things. But if the injector doesn't yet support initial roll yet, then we'll fix it manually.

Thanks Sphericvr and dcower for your help!
