### ISSUE TITLE
3D audio on youtube player

### ISSUE THREAD

**Issue by HubiWiWi** [google/spatial-media#64]
Hello,

As I read it on another thread below, it seems that youtube player is not yet compatible with ambisonics content. True right ?

Therefore, is there any other mean to render live 3D audio on youtube (particularly on headphones) currently ?

Thanks a lot for your answers

**Comment by dcower** [comment]
Hi @HubiWiWi,

That is correct; this is not currently supported on YouTube.

If you'd like to experiment with ambisonic audio, we've developed an Android app, [Jump Inspector](https://goo.gl/sN20N6), which lets you locally preview 360 videos with spatial audio. Please try it out and let us know (email address on the Play Store) if you have any feedback.

Thanks,
Dillon

**Comment by HubiWiWi** [comment]
Thank you for your answer.

I need to ask you something (maybe you won't be able or authorized to answer but it is quite important for my professional plans) :  is there a launch date for 360 audio support on Youtube ? Even an approximate schedule ?

Thanks a lot,

Sami

**Comment by dcower** [comment]
Spatial audio is now supported in YouTube. See [https://support.google.com/youtube/answer/6395969?hl=en](Use spatial audio in 360-degree and VR videos) from YouTube Help and [https://support.google.com/jump/answer/6399746?hl=en&ref_topic=6399824](Spatial Audio) from Jump Help.

**Comment by farrukhshahkhan** [comment]
Is ambisonic audio supported on live 360 streams also?
