### ISSUE TITLE
Are there any objective-c version for injecting metadata into video

### ISSUE THREAD

**Issue by tomtomtong** [google/spatial-media#65]
I am makeing a 360 video capturing app. Are there any objective-c version for injecting metadata into video? So I could implement in iOS app. Thx

**Comment by vade** [comment]
AVFoundation supports timed metadata in MOV containers, and arbitrary metadata as a serializable dictionary into MP4 and MOV containers. Timed metadata within MP4 is not officially supported as per my DTS ticket response. However, you can do it if you modify 3rd party libraries. I have some working examples at http://github.com/Synopsis/Synopsis

**Comment by tomtomtong** [comment]
Thx. You mean I could achieve this by using your libraries in the link?

**Comment by cievon** [comment]
hi, i meet this issue today, how to solve this problem about injecting metadata, thx

**Comment by cievon** [comment]
#135 I solved it.

**Comment by jamiesonpepper** [comment]
Closing older issues
