### ISSUE TITLE
Example references files for spec

### ISSUE THREAD

**Issue by vade** [google/spatial-media#67]
Hello.

I'm curious if there are any reference files for the timed metadata portion of the specification we can test our own implementations against, for writing as well as reading.

Thank you.

**Comment by dcower** [comment]
Hi @vade,

Unfortunately we don't have any reference files for that portion of the specification. I don't believe that portion of the specification is supported by any video streaming/playback services either. Out of curiosity, are you interested in writing tooling to support this or are you more interested in playing back content with it?

Feel free to reach out to me via email too if that works better for you: dcower@google.com

Thanks,
Dillon

**Comment by vade** [comment]
Both. I have a modified version of lib MP4V2 which supports my own timed metadata specification I am working on that works with moth MOV and MP4 wrappers. I don't use Apples boxed metadata format as per Quicktime / AVFoundations built in support, but my own binary stream using JSON.

I'm curious how you folks have implemented it as well as how many off the shelf playback software works with it. I have had an Apple DTS ticket for timed MP4 support within AVF, but they closed it. 

They have a VERY strict reading of the spec it seems. My solution is close to Googles (wow thats awesome to say, hahah) but has some nuances with older playback software. Im just curious if this spec does, and if so, to what end things can be mitigated.

Thank you.

For reference some of my in progress code for an analysis and metadata encoding pass is at :

https://github.com/Synopsis/Synopsis/tree/mp4v2

Forgive my language, I tend to be rather uh, you know, with my own projects :D

**Comment by kodabb** [comment]
@dcower has there been any update on releasing at least one reference sample by any chance?

**Comment by kodawah** [comment]
@jamiesonpepper why was this (and a bunch of other bugs) closed with no change or comment?

**Comment by jamiesonpepper** [comment]
@kodawah Sorry I was just cleaning up issues that had not had any updates or responses in over 5+ years in bulk. As the ability to use ffmpeg to inject metadata has improved and I am currently the only active maintainer and am mostly attempting to keep the binaries functional as newer releases of Python come out.

I'll be shifting things away from Python-TK to something web and Docker based starting out with a super simple container that requires using the CLI via docker exec  with mounted volumes over the next couple of weeks and will attempt to iterate on that to created a web-based UI that resembles the GTK UI.
