### ISSUE TITLE
How can I fix the 360-degree metadata application's code to get the video stay in fixed direction on mobile?

### ISSUE THREAD

**Issue by tuantrung2905** [google/spatial-media#69]
When I watch 360-degree videos on my phone, they rotate uncontrollably whenever I move the phone. So how can I fix the 360-degree metadata application's code to get the video stay in fixed direction on mobile?

**Comment by dcower** [comment]
Hi @tuantrung2905, this functionality is not supported by the Spherical Video metadata specification.
