### ISSUE TITLE
Youtube 360 metadata tool only has one StereoMode value

### ISSUE THREAD

**Issue by kodabb** [google/spatial-media#71]
If I input a "Left Right" file, I should definitely leave the "3D Top Bottom" box unselected, however when I do so, the StereoMode tag is not set in the metadata.

This is very ambiguous, as the specifications indicate that absence of StereoMode tag means "mono", not "Left Right". So there could be a lot of files incorrectly tagged with this software (which is detrimental to the adoption of spherical video).

I am not sure if the spec draft is wrong or if this is simply a bug in the metadata tool, but I hope it is something that will be addressed.

**Comment by kodabb** [comment]
To be more precise, the Youtube 360 metadata tool is the GUI version of the python script. The script itself works fine.

**Comment by suderman-google** [comment]
The GUI version of the Spherical Metadata Tool only supports top-bottom stereo. As a result when you load a left-right file it has no way to indicate that the video is left-right stereo and instead describes it as mono.

The reason the GUI tool does not support left-right stereo video is YouTube does not have support for the format. To avoid confusion on supported formats we are not planning to support left right video in the GUI tooling at this time.

**Comment by kodabb** [comment]
I understand the need to avoid creating files that the main consumer does not correctly understand, but the fact that users are not notified of relevant tags or that risk of tagging incorrectly a video is probably more confusing than displaying it in the GUI.

Consider it as a feature request, but please add a way to display the left-right mode, possibly disabling exporting if that flag is selected.

**Comment by dcower** [comment]
Hi @kodabb, thanks for the feedback! We're currently looking into improving the UI of the GUI version of the Spatial Media Metadata Injector and will take your comments into consideration. We definitely don't want users confused, so we're evaluating the best ways to give them the same (or more) functionality with less confusion. :)
