### ISSUE TITLE
youtube upload is not in HD. ( video manager says its HD, but will not playback in hd ) 

### ISSUE THREAD

**Issue by jsheffie** [google/spatial-media#72]
The youtube video manager shows the file in HD.
However the upload does not
Small Sample.
https://youtu.be/k5qDIr599kc

Large Sample.
https://youtu.be/AxR_MLAvgFI

The files that work on youtube have the following meta data:

$ python spatialmedia ~/Videos/2016/2016.04.03.Ranch_1st_theta-s/R0010009_er.MP4
Processing: /home/jds/Videos/2016/2016.04.03.Ranch_1st_theta-s/R0010009_er.MP4
Loaded file...
	Track 0
		Spherical = true
		Stitched = true
		ProjectionType = equirectangular
		StitchingSoftware = RICOH THETA::DualfishBlender.exe 2.1.0.2016.02.08
		SourceCount = 1
		Timestamp = 3542555697
	Track 1

The files that dont work have the following 'injected' metadata
$ python spatialmedia ~/Videos/360small3_i.mp4
Processing: /home/jds/Videos/360small3_i.mp4
Loaded file...
	Track 0
	Track 1
		Spherical = true
		Stitched = true
		StitchingSoftware = Spherical Metadata Tool
		ProjectionType = equirectangular

A bit more context: ( I have windows, mac, and linux all at my disposial. ) 
The Camera is a Theta S camera. I donwnloaded the file and converted it using theta
s windows application. I then brough those samples into lightworks and did the magic.
I exported ( every flavor of MP4 I can think of ;)

I then stitched in the spherical medadata using spatialmedia.

Any ideas of where I am going wrong?

p.s. these have had about a day to upload... so 'plenty of time' to farm out to there servers.

Thanks,
Jeff

**Comment by dcower** [comment]
Hi @jsheffie, sorry about the delay here. Please reopen if this is still an issue (I noticed the videos are now unavailable).
