### ISSUE TITLE
Please use a compact serialization for the video as is done for the audio.

### ISSUE THREAD

**Issue by lu-zero** [google/spatial-media#73]
Please consider using a normal struct serialized or a simple flat associative array using pascal strings and a 64bit value field (the video specification is only numbers and enum that I can see).

**Comment by haasn** [comment]
+1, the hardest part about implementing this is probably going to be writing a bug-free XML parser.

**Comment by kodabb** [comment]
I don't really get why this specification is in XML (and in the worst RDF variant too)

**Comment by mmedley** [comment]
+1

**Comment by dcower** [comment]
Thanks for the feedback! We have drafted [Spherical Video V2](https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md) to address this issue. We also created a mailing list, [spatial-media-discuss](https://groups.google.com/forum/#!forum/spatial-media-discuss) to discuss it and other specification issues.
