### ISSUE TITLE
Please use FuMa channel ordering

### ISSUE THREAD

**Issue by AdamSomers** [google/spatial-media#74]
Despite certain academic biases toward ACN (WYZX) channel ordering due to its algorithmic elegance (particularly in the case order > 1), [FuMa](http://www.york.ac.uk/inst/mustech/3d_audio/higher_order_ambisonics.pdf) (WXYZ) is the prevailing channel ordering used by b-format post-production tools such as:
- VVAudio Virtual Tetra Mic
- Blue Ripple Sound
- Ambisonics Toolkit
- TwoBigEars Spatial Workstation
- Dolby Atmos

Other tools (such as Harpex) allow for the option of FuMa in addition to ACN.

Blue Ripple is, in fact, the only fully featured higher order post-production toolset available today, and it uses FuMa for up to 3rd order.  This makes their HOA mixes compatible with traditional 1st-order WXYZ material without the need for conversion.

The choice of ACN will lead to confusion and errors in publishing, since almost all material authored in b-format will be "classic" 1st order b-format, or FuMa in the case of HOA.

**Comment by DrWig** [comment]
I agree, but I suspect it's too late to change from AmbiX now, and I have to admit that ACN makes much more sense from a channel ordering point of view, in the long term (higher orders).  I've written a Reaper JS plug-in to convert between FuMa->SN3D->N3D and also the ordering (you can specify normalisation and ordering of the input and output all separately).  I'll share soon.

However, I've just done a quick, simple test using a simple panned 1st order source and I'm not convinced Jump Inspector is binarualising correctly.  My 1st day of testing, though......
![wigwareambremap](https://cloud.githubusercontent.com/assets/717727/14644841/5fd9f86c-064b-11e6-8a2a-333a2569b196.jpg)

**Comment by joslloand** [comment]
Agreed... we can expect naive users to experience much confusion between the various encoding formats.

FYI, the [Ambisonic Toolkit](http://www.ambisonictoolkit.net/) will be offering support for use with AmbiX1 (ACN-SN3D, 1st order).

**Comment by kodabb** [comment]
@AdamSomers correct me if I'm wrong, but you can describe a fuma order if you change the channel_map to 0,2,3,1, no?

**Comment by dcower** [comment]
@kodabb FuMa ordering can be described via that method, but [maxN/FuMa normalization](https://en.wikipedia.org/wiki/Ambisonic_data_exchange_formats#maxN) is not covered in the specification (i.e., the user would need to scale their components / renormalize to SN3D in order to render correctly).
