### ISSUE TITLE
Can't eject audio metadata 

### ISSUE THREAD

**Issue by mheritz** [google/spatial-media#76]
Hello, 

I'm having issues injecting the spatial metadata.  It allows me to click on the box that I need to use, but will stay in an unless loop when saving.  The test clip is only 5 seconds long so it can't imagine it taking over 10min to add metadata, or am I wrong with this mindset?

**Comment by dcower** [comment]
Hi @mheritz,

Thanks for reporting this issue. Could you upload your test clip or email it to me ([myusername]@google.com)? I can then take a further look at the issue.

Dillon

**Comment by mheritz** [comment]
[Chilly_Water_Bounce.mp4.zip](https://github.com/google/spatial-media/files/229027/Chilly_Water_Bounce.mp4.zip)

**Comment by dcower** [comment]
@mheritz We should be able to get this figured out in time for that. Could you share what OS you're running? I'm able to inject Spatial Audio metadata in the clip you posted on OS X.

**Comment by mheritz** [comment]
@dcower Yosemite 10.10.5

**Comment by dcower** [comment]
@mheritz Could you re-download the [latest release](https://github.com/google/spatial-media/releases/latest) and try again? I believe the issue may be fixed.

**Comment by mheritz** [comment]
@dcower I just deleted and redownload the application and I am still haveing issues with injecting the metadata.  Attached is a screenshot of what it get's stuck on with a screen recording on my workflow.  
[Screen Capture 2016-04-22 at 22.31.23.mov.zip](https://github.com/google/spatial-media/files/232772/Screen.Capture.2016-04-22.at.22.31.23.mov.zip)

On top of that, the source code still says 2.0.  Wouldn't the update you provide change it?  Just want to make sure I'm not redownloading the same file source again.
![screen shot 2016-04-22 at 10 27 01 pm](https://cloud.githubusercontent.com/assets/18584296/14758834/554bb160-08da-11e6-8122-f392c2ea636f.png)

**Comment by dcower** [comment]
@mheritz Ah! Thank you for the screenshot -- that actually helps a lot. I've uploaded a new version; could you test that and see if the issue is resolved? Apologies this is taking so many iterations.

Regarding the version number, since I'm just swapping out the release .zip, the version number stays constant.

**Comment by mheritz** [comment]
@dcower This seemed to do the trick.  THANK YOU SO MUCH FOR WORKING WITH ME ON THIS ISSUE!!!!

**Comment by dcower** [comment]
Glad to hear it! Thanks for being persistent. :)
