### ISSUE TITLE
Mixed Spatial / Non Spatial Audio

### ISSUE THREAD

**Issue by evanmang** [google/spatial-media#77]
Hi!

I noticed that support for the spatial audio is now live in the android youtube app! This is great! Any timeline on browser / ios support?

Also, as a sound designer, I want to note that I would LOVE to see support for playback of a B-Format spatialized mix with a stereo non-spatialized mix, for combining spatialized elements with non-spatial audio (backgrounds / voiceover / non diegetic music) This would go a long way to making the 360 audio experience fantastic on youtube, and give creators a lot of freedom in making great content.

thanks!

Evan

**Comment by dcower** [comment]
Hey @evanmang!

I can't share any timelines on spatial audio support for other platforms unfortunately.

Regarding playback of non-spatialized audio alongside spatialized audio, we've drafted support in the [Spatial Audio](https://github.com/google/spatial-media/blob/master/docs/spatial-audio-rfc.md) metadata specification for that under the [Non-Diegetic Audio Box](https://github.com/google/spatial-media/blob/master/docs/spatial-audio-rfc.md#non-diegetic-audio-box-sand). Let us know what you think!

We also created a mailing list, [spatial-media-discuss](https://groups.google.com/forum/#!forum/spatial-media-discuss), to discuss the spatial media specifications. Feel free to comment there too!

Thanks,
Dillon

**Comment by evanmang** [comment]
@dcower that looks great! looking forward to that support being added in the live player.
