### ISSUE TITLE
Initial view port  invalid

### ISSUE THREAD

**Issue by Dhenty** [google/spatial-media#78]
Hi,
I am add initial view port degree info in mov container and upload to YouTube, it isn't work! The video parse info by spatialmedia:
Processing: G:\VIDEO\20120612_231444M.MOV
Loaded file...
        Track 0
                Spherical = true
                Stitched = true
                StitchingSoftware = Icatchtek 6350 software
                ProjectionType = equirectangular
                InitialViewHeadingDegrees = -90
                InitialViewPitchDegrees = 180
                InitialViewRollDegrees = 45
        Track 1

Thanks!

**Comment by dcower** [comment]
Hi @Dhenty,

Initial view heading/pitch/roll degrees is not currently supported by YouTube. Apologies for the confusion here. The current solution for that involves modifying the video in video editing software.

Dillon

**Comment by paulcanning** [comment]
Do you have any information regarding your statement "Initial view heading/pitch/roll degrees is not currently supported by YouTube."?

We have a video that has dual purpose, being viewed on YouTube and being used in a projection mapping event. For YouTube, we'd need to adjust the heading setting, rather then rendering two videos.

**Comment by adiantek** [comment]
any info about youtube? Is it supported?
