### ISSUE TITLE
launches and quits

### ISSUE THREAD

**Issue by megamaydaa** [google/spatial-media#80]
hello, i just downloaded the Spatial Media Metadata Injector app on two different macs (10.7.5 and 10.8.5) and on both machines the application quit immediately after launching. Is there a compatibility issue? I'm not sure what the explanation could be. I tried to use the python script as well but am not very familiar with the command line and ran into a syntax error.... 

Thank you for any advice with this issue.

**Comment by wjbarber** [comment]
I'm having the same issue (mac v10.10.5), but it just hangs there when saving out a test file, nothing big. I've also tried the python script with the same problem. Can anyone offer any help on this please?

**Comment by dcower** [comment]
@megamaydaa @wjbarber Sorry for the convenience, and thanks for reporting. Could you share a test file that exhibits the issue? You can attach it here or email it to me (<myusername>@google.com).

**Comment by wjbarber** [comment]
Not at my machine right now but I will send you something tomorrow morning. First thing. Thanks for getting back to us.
Will

Sent from Outlook Mobile<https://aka.ms/blhgte>

**Comment by dcower** [comment]
This issue should be fixed with the latest release; please re-download if you are still encountering the issue. Thanks again for reporting!
