### ISSUE TITLE
Metadata injection won't work anymore ?

### ISSUE THREAD

**Issue by Binome59** [google/spatial-media#81]
Hello,

On the spatialmedia folder, the readme.md file tells how to inject 360 metadata to a video : 
`
python spatialmedia -i myIn.mp4 myOut.mp4
`

However, this command doesn't work : i get an error : 
`
python: can't open file 'spatialmedia': [Errno 2] No such file or directory
`

Read somewhere than i should call this script instead : 
`
python metadata_utils.py -i myIn.mp4 myOut.mp4
`
but i get : 
`
Traceback (most recent call last):
  File "metadata_utils.py", line 27, in <module>
    from spatialmedia import mpeg
ImportError: No module named spatialmedia
`
All those commands are run from the spatial-media/spatialmedia folder, where there is, among others, the metadata_utils.py python script. 

Did i miss something obvious ?
thanks !
Oliv.

**Comment by suderman-google** [comment]
Hi Binome!

Try running `python spatialmedia -i myIn.mp4 myOut.mp4` from one folder higher (spatial-media/) and tell me if that works.

**Comment by Binome59** [comment]
Hello,

Yes, found it just after i published that issue, my bad, it's my total mistake.
By running it one folder above, it works like a charm !
Thanks a lot for your help, indeed !
Oliv.
