### ISSUE TITLE
C++/C version for this repository

### ISSUE THREAD

**Issue by tomtomtong** [google/spatial-media#82]
Hello. I would like to integrate the metadata injecting function into my C++ program.
Are there any C++/C version for this repository? Thx.

**Comment by wenwu2015** [comment]
I  write  a java version for this repository,you can try it ,https://github.com/wenwu2015/mp4parse

**Comment by tomtomtong** [comment]
Thx. I would like to implement metadata injecting function into my xcode project. Do you have other suggestions?

**Comment by VarolOkan** [comment]
I just started a C++ port for this tool, as I want to use it in an environment where Python / Jython may not simply be added.
At this time it is still non-functional due to time constraints. Please feel free to contribute.
https://github.com/VarolOkan/spatial-media/tree/master/spatialmedia

**Comment by tomtomtong** [comment]
VarolOkan

Thank for your hardworking. Does the C++ port work now?

**Comment by VarolOkan** [comment]
The port is complete and I am working on the unit testing atm. 

So not yet but hopefully soon.

Hello is welcome since I am only able to spend time on it on my weekends.

**Comment by VarolOkan** [comment]
Initial working version is now available ( v 2.1 )

**Comment by Roadkitten** [comment]
Thank you and Hellooooo

**Comment by ajaykt665** [comment]
> Initial working version is now available ( v 2.1 ) 
> https://github.com/VarolOkan/spatial-media/releases/tag/v2.1

Hi Varol,
does the c++ port have a support in injecting audio metadata(Ambisonic) apart from video metadata?
I tried to run the CPP port on one of the 360 video where the video metadata(projection) got injected.However, i was not able to inject audio metadata(channel=Ambisonics).Please help me how to do this.
