### ISSUE TITLE
Kodak Sp 360 4k video editing (external edditor not from Kodak) 

### ISSUE THREAD

**Issue by Ahurtado12** [google/spatial-media#87]
Hi, I am having problems with editing 360 videos from a Sp 360 4k camera, when I edit from an external software all I want to do is make the video file 360 compatible for youtube, but when I run it trough Google's Metadata software it makes it 360 but leaves a black hole on top of the video. This new version of Metadata has options, I never got the old version but I'm thinking the old version would have worked due to it being a click of a button, the new version has options. Does anyone know what I'm talking about? Pls help. Thx

**Comment by dcower** [comment]
Hi @Ahurtado12, could you share a sample video or link on YouTube? Feel free to reach out to me privately ([my username]@google.com). The issue might be that your video has black bars at the top and bottom. Could you check it in VLC or another video playback app and see if your video takes up the entire frame?

**Comment by dcower** [comment]
Hi @Ahurtado12, I'm closing this for now. Please reopen if you have additional information. Thanks.
