### ISSUE TITLE
v2 binary video data support in source code

### ISSUE THREAD

**Issue by jfurton** [google/spatial-media#88]
It appears that the current python sample code only handles reading or writing the V1 XML format instead if the V2 binary for videos metadata. 
Is there a plan to update the python code to use V2? Similarly the Windows EXE appears to use V1 video format. 

John

**Comment by suderman-google** [comment]
The V2 specification is still being drafted and subject to change. Once we have finalized the format we will be releasing tooling for the format.

**Comment by kodabb** [comment]
@suderman-google Hi, is there any progress in updating the script? Would you consider accepting a patch for it?
