### ISSUE TITLE
Error message for Mac

### ISSUE THREAD

**Issue by graphismecieldazur** [google/spatial-media#95]
Hello, I try to open a 360° video (Kodak Prixpro SP360 4K) in Spatial Media and it gives me this error message after I select a video (and I can't check any boxes):
![spatial machin error](https://cloud.githubusercontent.com/assets/19857609/15965191/ad7b9658-2f1c-11e6-9e52-623bd029ee7e.jpg)

I'm using OSX El Capitan 10.11.4 and I downloaded the very last version of the app.
Thank you for your help!

**Comment by suderman-google** [comment]
Hi graphismecieldazur,

Just a couple quick questions:
Does this only occur when opening the file?
What is the name of the video file you are using?
Would you mind providing the video file so we can test on this end?

**Comment by graphismecieldazur** [comment]
Hi,
Thanks for your message…
Don’t know how, it’s working now. I installed and reinstalled several times and now it’s working.
Though I’m not sure it inject the metadata in the right way, as in YouTube it doesn’t appear as a 360° video, but maybe because the files are not well saved in Premiere… still have to check this.
The name of the file is generic, 100_0010.mp4
Thank you for you help,
Best regards,

Olivier Vin
Graphisme @ Ciel d’Azur
<Olivier%20Vin
Graphisme%20@%20Ciel%20d’Azur
www.cieldazur.com>cieldazur.com<http://www.cieldazur.com>
Suivez-nous sur Facebook<https://www.facebook.com/PurAlo%C3%A9-Une-plante-pour-la-vie-1021589057898859/?fref=ts>

De : suderman-google <notifications@github.com<mailto:notifications@github.com>>
Répondre à : google/spatial-media <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : vendredi 10 juin 2016 18:46
À : google/spatial-media <spatial-media@noreply.github.com<mailto:spatial-media@noreply.github.com>>
Cc : Olivier Vin <graphisme@cieldazur.com<mailto:graphisme@cieldazur.com>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [google/spatial-media] Error message for Mac (#95)


Hi graphismecieldazur,

Just a couple quick questions:
Does this only occur when opening the file?
What is the name of the video file you are using?
Would you mind providing the video file so we can test on this end?

**Comment by graphismecieldazur** [comment]
Oh, and on the Spatial Media Metadata Tool, I don't have the "spherical" button, is it normal ?
I only have stereoscopic 3D and spatial audio.
thanks

**Comment by suderman-google** [comment]
We recently updated the application (which included removing the spherical checkbox). The difference was purely aesthetic so you should not see any difference in functionality.

One possibility for the issue is if the directory it is in contains any UTF-8 character, there is a known issue with paths that contain certain characters. As a workaround could you try placing the file at the root or some other path with only non-UTF8 characters?

**Comment by graphismecieldazur** [comment]
Ok thanks for the precision.
There are no special characters or UTF-8. I use simple names as "video 360", or "rushes" for the folders, and keep it simple for the files names: test01.mp4...
Weird, I'll keep on experimenting, maybe the problem comes from the files themselves... I'm waiting for an answer from Kodak too.
Thank you!

**Comment by xteorodriguezx** [comment]
Hello, I have the same problem and I never had that problem before with the other videos. I have one 360fly 4k and the video dimensions exported are 2560x1280.
Is there a possibility that the problem comes when exporting from premiere?

![captura de pantalla 2016-06-18 a las 11 58 02 a m](https://cloud.githubusercontent.com/assets/20016308/16172335/02cfa88a-354c-11e6-928f-0360de1b1b0e.png)

**Comment by pwroberts** [comment]
Hi @graphismecieldazur,

I've uploaded a new OS X binary with a fix for the UnicodeEncodeError error message you were seeing. You can download it from https://github.com/google/spatial-media/releases/download/v2.0/360.Video.Metadata.Tool.mac.zip.

Could you try it out and let me know if you still see the error?

Thanks for your help!

Paul

**Comment by graphismecieldazur** [comment]
Hi Paul,
Thanks for your message!
Yes it works fine now, thank you :-)

**Comment by pwroberts** [comment]
Great - thanks for confirming!
