### ISSUE TITLE
How do I change CroppedArea by using the command?

### ISSUE THREAD

**Issue by tomtomtong** [google/spatial-media#96]
Hello. I would like to insert metadata into a panorama video. How do I change the croppedArea by using the command? Thank for any help.

**Comment by suderman-google** [comment]
Hey tomtomtong,

The command line utility has a --crop flag you can use. You can use it as follows

python spatialmedia --inject --crop <a>:<b>:<c>:<d>:<e>:<f> input.mp4 output.mp4

The <i> values are integers measuring the crop in pixels. Each value is as follows
<a> - CroppedAreaImageWidthPixels
<b> - CroppedAreaImageHeightPixels
<c> - FullPanoWidthPixels
<d> - FullPanoHeightPixels
<e> - CroppedAreaLeftPixels
<f> - CroppedAreaTopPixels

So assuming you had a 1024 by 256 image that was 360 degrees by 90 degrees, the values would be as follows:

python spatialmedia --inject --crop 1024:256:1024:512:0:128 input.mp4 output.mp4

As an aside: if you intend to use the file with YouTube, the platform does not support cropping metadata at this point in time. Hope this was helpful and please follow up if you have trouble.

**Comment by BrianLeishman** [comment]
Has support from YouTube changed at all regarding adjusting the crop amount?
