### ISSUE TITLE
Installation of latest 2.0 version flagged as trojan

### ISSUE THREAD

**Issue by Clembotic** [google/spatial-media#97]
When I download and the unzip the app, my antivirus throws a virus (trojan) warning. Anyone else seeing this?

**Comment by pwroberts** [comment]
Hi @Clembotic,

Thanks for reporting this - we’re looking into it. PyInstaller’s bootloader seems to occasionally trigger a false positive from the “generic Trojan” heuristic in various AV software. There are many reports of this on the PyInstaller GitHub going back several years, e.g. https://github.com/pyinstaller/pyinstaller/issues/1692, https://github.com/pyinstaller/pyinstaller/issues/847, and https://github.com/pyinstaller/pyinstaller/issues/603.

In the meantime, if this is preventing you from using the metadata injector tool, you can always run the tool directly from the source code:

- Install Python 2 from https://www.python.org/
- Download and extract the metadata injector source code from https://github.com/google/spatial-media/archive/v2.0.zip
- From the "spatialmedia" directory inside the extracted archive, run "gui.py" (double click it in Windows Explorer or run "python gui.py" from the command prompt).

Thanks again!

Paul

**Comment by Clembotic** [comment]
Thanks for the reply and information, Paul. I figured (and hoped) it was a false positive. Thanks for confirming. I'll go the python route you suggest in the meantime.

**Comment by pwroberts** [comment]
It looks like the PyInstaller AV warnings mostly affect 32-bit PyInstaller-generated binaries. I've put a new, 64-bit binary on [the 2.0 release page](https://github.com/google/spatial-media/releases/tag/v2.0). 32-bit Windows users can still run the injector from source by installing Python.

Thanks again for reporting this, and please re-open this issue if you see any more AV warnings.

**Comment by Clembotic** [comment]
I tried the new binary and all good! No AV warnings. Thanks!
